// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package step

import (
	"context"

	"github.com/NVIDIA/nodewright/agent/internal/execution"
	"github.com/NVIDIA/nodewright/agent/internal/step"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStep creates a new instance of MockStep. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStep(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStep {
	mock := &MockStep{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStep is an autogenerated mock type for the Step type
type MockStep struct {
	mock.Mock
}

type MockStep_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStep) EXPECT() *MockStep_Expecter {
	return &MockStep_Expecter{mock: &_m.Mock}
}

// Encode provides a mock function for the type MockStep
func (_mock *MockStep) Encode() ([]byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStep_Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encode'
type MockStep_Encode_Call struct {
	*mock.Call
}

// Encode is a helper method to define mock.On call
func (_e *MockStep_Expecter) Encode() *MockStep_Encode_Call {
	return &MockStep_Encode_Call{Call: _e.mock.On("Encode")}
}

func (_c *MockStep_Encode_Call) Run(run func()) *MockStep_Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStep_Encode_Call) Return(bytes []byte, err error) *MockStep_Encode_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockStep_Encode_Call) RunAndReturn(run func() ([]byte, error)) *MockStep_Encode_Call {
	_c.Call.Return(run)
	return _c
}

// ExecutionMetadata provides a mock function for the type MockStep
func (_mock *MockStep) ExecutionMetadata() step.ExecutionMetadata {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExecutionMetadata")
	}

	var r0 step.ExecutionMetadata
	if returnFunc, ok := ret.Get(0).(func() step.ExecutionMetadata); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(step.ExecutionMetadata)
	}
	return r0
}

// MockStep_ExecutionMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecutionMetadata'
type MockStep_ExecutionMetadata_Call struct {
	*mock.Call
}

// ExecutionMetadata is a helper method to define mock.On call
func (_e *MockStep_Expecter) ExecutionMetadata() *MockStep_ExecutionMetadata_Call {
	return &MockStep_ExecutionMetadata_Call{Call: _e.mock.On("ExecutionMetadata")}
}

func (_c *MockStep_ExecutionMetadata_Call) Run(run func()) *MockStep_ExecutionMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStep_ExecutionMetadata_Call) Return(executionMetadata step.ExecutionMetadata) *MockStep_ExecutionMetadata_Call {
	_c.Call.Return(executionMetadata)
	return _c
}

func (_c *MockStep_ExecutionMetadata_Call) RunAndReturn(run func() step.ExecutionMetadata) *MockStep_ExecutionMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// Fingerprint provides a mock function for the type MockStep
func (_mock *MockStep) Fingerprint() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Fingerprint")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStep_Fingerprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fingerprint'
type MockStep_Fingerprint_Call struct {
	*mock.Call
}

// Fingerprint is a helper method to define mock.On call
func (_e *MockStep_Expecter) Fingerprint() *MockStep_Fingerprint_Call {
	return &MockStep_Fingerprint_Call{Call: _e.mock.On("Fingerprint")}
}

func (_c *MockStep_Fingerprint_Call) Run(run func()) *MockStep_Fingerprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStep_Fingerprint_Call) Return(s string, err error) *MockStep_Fingerprint_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStep_Fingerprint_Call) RunAndReturn(run func() (string, error)) *MockStep_Fingerprint_Call {
	_c.Call.Return(run)
	return _c
}

// Idempotence provides a mock function for the type MockStep
func (_mock *MockStep) Idempotence() step.Idempotence {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Idempotence")
	}

	var r0 step.Idempotence
	if returnFunc, ok := ret.Get(0).(func() step.Idempotence); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(step.Idempotence)
	}
	return r0
}

// MockStep_Idempotence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Idempotence'
type MockStep_Idempotence_Call struct {
	*mock.Call
}

// Idempotence is a helper method to define mock.On call
func (_e *MockStep_Expecter) Idempotence() *MockStep_Idempotence_Call {
	return &MockStep_Idempotence_Call{Call: _e.mock.On("Idempotence")}
}

func (_c *MockStep_Idempotence_Call) Run(run func()) *MockStep_Idempotence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStep_Idempotence_Call) Return(idempotence step.Idempotence) *MockStep_Idempotence_Call {
	_c.Call.Return(idempotence)
	return _c
}

func (_c *MockStep_Idempotence_Call) RunAndReturn(run func() step.Idempotence) *MockStep_Idempotence_Call {
	_c.Call.Return(run)
	return _c
}

// Path provides a mock function for the type MockStep
func (_mock *MockStep) Path() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Path")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockStep_Path_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Path'
type MockStep_Path_Call struct {
	*mock.Call
}

// Path is a helper method to define mock.On call
func (_e *MockStep_Expecter) Path() *MockStep_Path_Call {
	return &MockStep_Path_Call{Call: _e.mock.On("Path")}
}

func (_c *MockStep_Path_Call) Run(run func()) *MockStep_Path_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStep_Path_Call) Return(s string) *MockStep_Path_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockStep_Path_Call) RunAndReturn(run func() string) *MockStep_Path_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockStep
func (_mock *MockStep) Run(context1 context.Context, config execution.Config) (execution.Status, error) {
	ret := _mock.Called(context1, config)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 execution.Status
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, execution.Config) (execution.Status, error)); ok {
		return returnFunc(context1, config)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, execution.Config) execution.Status); ok {
		r0 = returnFunc(context1, config)
	} else {
		r0 = ret.Get(0).(execution.Status)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, execution.Config) error); ok {
		r1 = returnFunc(context1, config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStep_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockStep_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - context1 context.Context
//   - config execution.Config
func (_e *MockStep_Expecter) Run(context1 interface{}, config interface{}) *MockStep_Run_Call {
	return &MockStep_Run_Call{Call: _e.mock.On("Run", context1, config)}
}

func (_c *MockStep_Run_Call) Run(run func(context1 context.Context, config execution.Config)) *MockStep_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 execution.Config
		if args[1] != nil {
			arg1 = args[1].(execution.Config)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStep_Run_Call) Return(status execution.Status, err error) *MockStep_Run_Call {
	_c.Call.Return(status, err)
	return _c
}

func (_c *MockStep_Run_Call) RunAndReturn(run func(context1 context.Context, config execution.Config) (execution.Status, error)) *MockStep_Run_Call {
	_c.Call.Return(run)
	return _c
}

// WithVersions provides a mock function for the type MockStep
func (_mock *MockStep) WithVersions(previous string, current string) step.Step {
	ret := _mock.Called(previous, current)

	if len(ret) == 0 {
		panic("no return value specified for WithVersions")
	}

	var r0 step.Step
	if returnFunc, ok := ret.Get(0).(func(string, string) step.Step); ok {
		r0 = returnFunc(previous, current)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(step.Step)
		}
	}
	return r0
}

// MockStep_WithVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithVersions'
type MockStep_WithVersions_Call struct {
	*mock.Call
}

// WithVersions is a helper method to define mock.On call
//   - previous string
//   - current string
func (_e *MockStep_Expecter) WithVersions(previous interface{}, current interface{}) *MockStep_WithVersions_Call {
	return &MockStep_WithVersions_Call{Call: _e.mock.On("WithVersions", previous, current)}
}

func (_c *MockStep_WithVersions_Call) Run(run func(previous string, current string)) *MockStep_WithVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStep_WithVersions_Call) Return(step1 step.Step) *MockStep_WithVersions_Call {
	_c.Call.Return(step1)
	return _c
}

func (_c *MockStep_WithVersions_Call) RunAndReturn(run func(previous string, current string) step.Step) *MockStep_WithVersions_Call {
	_c.Call.Return(run)
	return _c
}
