# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Node
metadata:
  labels:
    skyhook.nvidia.com/test-node: skyhooke2e
    skyhook.nvidia.com/status_uninstall-upgrade-skyhook: in_progress
  annotations:
    ("skyhook.nvidia.com/nodeState_uninstall-upgrade-skyhook" && parse_json("skyhook.nvidia.com/nodeState_uninstall-upgrade-skyhook")):
      {
        "dogs|1.2.5": {
            "name": "dogs",
            "version": "1.2.5",
            "image": "ghcr.io/nvidia/skyhook/agentless",
            "stage": "uninstall",
            "state": "in_progress"
        },
        "nullptr|2.0.1": {
            "name": "nullptr",
            "version": "2.0.1",
            "image": "ghcr.io/nvidia/skyhook/agentless",
            "stage": "uninstall",
            "state": "in_progress"
        },
      }
    skyhook.nvidia.com/status_uninstall-upgrade-skyhook: in_progress
  (!taints || length(taints)==`0` || (taints && !not_null(taints))): true ## taints should be empty or not exist
status:
  (conditions[?type == 'skyhook.nvidia.com/uninstall-upgrade-skyhook/NotReady']):
  - reason: "Incomplete"
    status: "True"
  (conditions[?type == 'skyhook.nvidia.com/uninstall-upgrade-skyhook/Erroring']):
  - reason: "Not Erroring"
    status: "False"
---
kind: Pod
apiVersion: v1
metadata:
  namespace: skyhook
  labels:
    skyhook.nvidia.com/name: uninstall-upgrade-skyhook
    skyhook.nvidia.com/package: dogs-1.2.5
  annotations:
    ("skyhook.nvidia.com/package" && parse_json("skyhook.nvidia.com/package")):
      {
        "name": "dogs",
        "version": "1.2.5",
        "skyhook": "uninstall-upgrade-skyhook",
        "stage": "uninstall",
        "image": "ghcr.io/nvidia/skyhook/agentless"
      }
  ownerReferences:
    - apiVersion: skyhook.nvidia.com/v1alpha1
      kind: Skyhook
      name: uninstall-upgrade-skyhook
spec:
  initContainers:
    - name: dogs-init
    - name: dogs-uninstall
      args:
        ([0]): uninstall
        ([1]): /root
        (length(@)): 3
    - name: dogs-uninstallcheck
      args:
        ([0]): uninstall-check
        ([1]): /root
        (length(@)): 3
---
kind: Pod
apiVersion: v1
metadata:
  namespace: skyhook
  labels:
    skyhook.nvidia.com/name: uninstall-upgrade-skyhook
    skyhook.nvidia.com/package: nullptr-2.0.1
  annotations:
    ("skyhook.nvidia.com/package" && parse_json("skyhook.nvidia.com/package")):
      {
        "name": "nullptr",
        "version": "2.0.1",
        "skyhook": "uninstall-upgrade-skyhook",
        "stage": "uninstall",
        "image": "ghcr.io/nvidia/skyhook/agentless"
      }
  ownerReferences:
    - apiVersion: skyhook.nvidia.com/v1alpha1
      kind: Skyhook
      name: uninstall-upgrade-skyhook
spec:
  initContainers:
    - name: nullptr-init
    - name: nullptr-uninstall
      args:
        ([0]): uninstall
        ([1]): /root
        (length(@)): 3
    - name: nullptr-uninstallcheck
      args:
        ([0]): uninstall-check
        ([1]): /root
        (length(@)): 3
---
apiVersion: v1
kind: Node
metadata:
  labels:
    skyhook.nvidia.com/test-node: skyhooke2e
    skyhook.nvidia.com/status_uninstall-upgrade-skyhook: complete
  annotations:
    skyhook.nvidia.com/nodeState_uninstall-upgrade-skyhook: '{}'
    skyhook.nvidia.com/status_uninstall-upgrade-skyhook: complete
status:
  (conditions[?type == 'skyhook.nvidia.com/uninstall-upgrade-skyhook/NotReady']):
  - reason: "Complete"
    status: "False"
  (conditions[?type == 'skyhook.nvidia.com/uninstall-upgrade-skyhook/Erroring']):
  - reason: "Not Erroring"
    status: "False"
---
apiVersion: skyhook.nvidia.com/v1alpha1
kind: Skyhook
metadata:
  name: uninstall-upgrade-skyhook
status:
  status: complete
  observedGeneration: 6
  completeNodes: 1/1
  packageList: ""
  nodesInProgress: 0
  nodeState: 
    (values(@)): {}
  nodeStatus:
   # grab values should be one and is complete
    (values(@)):
      - complete
