# 
# LICENSE START
#
#    Copyright (c) NVIDIA CORPORATION.  All rights reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
# LICENSE END
# 







apiVersion: v1
kind: Node
metadata:
  labels:
    skyhook.nvidia.com/test-node: skyhooke2e
    skyhook.nvidia.com/status_uninstall-upgrade-skyhook: complete
  annotations:
    ("skyhook.nvidia.com/nodeState_uninstall-upgrade-skyhook" && parse_json("skyhook.nvidia.com/nodeState_uninstall-upgrade-skyhook")):
      {
        "cats|6.2.0": {
            "name": "cats",
            "version": "6.2.0",
            "image": "ghcr.io/nvidia/skyhook/agentless",
            "stage": "config",
            "state": "complete"
        },
        "dogs|1.2.6": {
            "name": "dogs",
            "version": "1.2.6",
            "image": "ghcr.io/nvidia/skyhook/agentless",
            "stage": "post-interrupt",
            "state": "complete"
        },
        "nullptr|2.0.0": {
            "name": "nullptr",
            "version": "2.0.0",
            "image": "ghcr.io/nvidia/skyhook/agentless",
            "stage": "post-interrupt",
            "state": "complete"
        }
      }
    skyhook.nvidia.com/status_uninstall-upgrade-skyhook: complete
status:
  (conditions[?type == 'skyhook.nvidia.com/uninstall-upgrade-skyhook/NotReady']):
  - reason: "Complete"
    status: "False"
  (conditions[?type == 'skyhook.nvidia.com/uninstall-upgrade-skyhook/Erroring']):
  - reason: "Not Erroring"
    status: "False"
---
apiVersion: skyhook.nvidia.com/v1alpha1
kind: Skyhook
metadata:
  name: uninstall-upgrade-skyhook
status:
  status: complete
  completeNodes: 1/1
  packageList: cats:6.2.0,dogs:1.2.6,nullptr:2.0.0
  nodesInProgress: 0
  observedGeneration: 2
  nodeState:
    (values(@)):
      - dogs|1.2.6:
          name: dogs
          state: complete
          version: '1.2.6'
          stage: post-interrupt
          image: ghcr.io/nvidia/skyhook/agentless
        nullptr|2.0.0:
          name: nullptr
          state: complete
          version: '2.0.0'
          stage: post-interrupt
          image: ghcr.io/nvidia/skyhook/agentless
        cats|6.2.0:
          name: cats
          state: complete
          version: '6.2.0'
          stage: config
          image: ghcr.io/nvidia/skyhook/agentless
  nodeStatus:
   # grab values should be one and is complete
    (values(@)):
      - complete
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: uninstall-upgrade-skyhook-nullptr-2.0.0
  namespace: skyhook
  labels:
    skyhook.nvidia.com/name: uninstall-upgrade-skyhook
  ownerReferences:
  - apiVersion: skyhook.nvidia.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Skyhook
    name: uninstall-upgrade-skyhook
data:
  game.properties: |
    enemies=aliens
    lives=3
    enemies.cheat=true
    enemies.cheat.level=noGoodRotten
  ui.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
    how.nice.to.look=fairlyNice
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: uninstall-upgrade-skyhook-dogs-1.2.6
  namespace: skyhook
  labels:
    skyhook.nvidia.com/name: uninstall-upgrade-skyhook
  ownerReferences:
  - apiVersion: skyhook.nvidia.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Skyhook
    name: uninstall-upgrade-skyhook
data:
  game.properties: |
    enemies=aliens
    lives=3
    enemies.cheat=true
    enemies.cheat.level=noGoodRotten
  ui.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
    how.nice.to.look=fairlyNice