---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-skyhook-nvidia-com-v1alpha1-skyhook
  failurePolicy: Fail
  name: mskyhook.kb.io
  rules:
  - apiGroups:
    - skyhook.nvidia.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - skyhooks
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-skyhook-nvidia-com-v1alpha1-skyhook
  failurePolicy: Fail
  name: vskyhook.kb.io
  rules:
  - apiGroups:
    - skyhook.nvidia.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - skyhooks
  sideEffects: None
