// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package config

import (
	"github.com/NVIDIA/nodewright/agent/internal/schema"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSchemaValidator creates a new instance of MockSchemaValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSchemaValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSchemaValidator {
	mock := &MockSchemaValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSchemaValidator is an autogenerated mock type for the SchemaValidator type
type MockSchemaValidator struct {
	mock.Mock
}

type MockSchemaValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSchemaValidator) EXPECT() *MockSchemaValidator_Expecter {
	return &MockSchemaValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type MockSchemaValidator
func (_mock *MockSchemaValidator) Validate(data []byte, v schema.SchemaVersion) error {
	ret := _mock.Called(data, v)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte, schema.SchemaVersion) error); ok {
		r0 = returnFunc(data, v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSchemaValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockSchemaValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - data []byte
//   - v schema.SchemaVersion
func (_e *MockSchemaValidator_Expecter) Validate(data interface{}, v interface{}) *MockSchemaValidator_Validate_Call {
	return &MockSchemaValidator_Validate_Call{Call: _e.mock.On("Validate", data, v)}
}

func (_c *MockSchemaValidator_Validate_Call) Run(run func(data []byte, v schema.SchemaVersion)) *MockSchemaValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 schema.SchemaVersion
		if args[1] != nil {
			arg1 = args[1].(schema.SchemaVersion)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSchemaValidator_Validate_Call) Return(err error) *MockSchemaValidator_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSchemaValidator_Validate_Call) RunAndReturn(run func(data []byte, v schema.SchemaVersion) error) *MockSchemaValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}
