# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: skyhook.nvidia.com/v1alpha1
kind: Skyhook
metadata:
  labels:
    app.kubernetes.io/part-of: skyhook-operator
    app.kubernetes.io/created-by: skyhook-operator
  name: demo
  annotations:
    skyhook.nvidia.com/pause: "false"
    skyhook.nvidia.com/disable: "false"
spec:
  nodeSelectors:
    matchLabels:
      eks.amazonaws.com/nodegroup: demo
  interruptionBudget: 
    percent: 100
  podNonInterruptLabels:
    matchLabels:
      app: skyhook-demo-workload
  packages:
    baz:
      version: 1.1.0
      image: ghcr.io/nvidia/skyhook-packages/shellscript
      interrupt:
        type: reboot
        # type: service
        # services:
        #   - cron
      configMap:
        config.yaml: |-
          #!/bin/bash
          sleep 100
        config_check.yaml: |-
          #!/bin/bash
          sleep 100
