# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Assert kind-worker2 completes after unblocking

# 1. Apply stage pod on kind-worker2
apiVersion: v1
kind: Pod
metadata:
  namespace: skyhook
  labels:
    skyhook.nvidia.com/name: runtime-required
    skyhook.nvidia.com/package: spencer-3.2.3
  annotations:
    ("skyhook.nvidia.com/package" && parse_json("skyhook.nvidia.com/package").stage == 'apply'): true
spec:
  nodeName: kind-worker2
---
# 2. Config stage pod on kind-worker2
apiVersion: v1
kind: Pod
metadata:
  namespace: skyhook
  labels:
    skyhook.nvidia.com/name: runtime-required
    skyhook.nvidia.com/package: spencer-3.2.3
  annotations:
    ("skyhook.nvidia.com/package" && parse_json("skyhook.nvidia.com/package").stage == 'config'): true
spec:
  nodeName: kind-worker2
---
# 3. kind-worker2 node complete with taint removed
apiVersion: v1
kind: Node
metadata:
  name: kind-worker2
  labels:
    skyhook.nvidia.com/status_runtime-required: complete
  annotations:
    skyhook.nvidia.com/status_runtime-required: complete
spec:
  (!taints || length(taints[?key == 'skyhook.nvidia.com' && effect == 'NoSchedule' && value == 'runtime-required'])==`0`): true
