apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: skyhook-operator-leader-election-role
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: skyhook-operator
    app.kubernetes.io/part-of: skyhook-operator
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: skyhook-operator-leader-election-rolebinding
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: skyhook-operator
    app.kubernetes.io/part-of: skyhook-operator
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: skyhook-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "chart.fullname" . }}-controller-manager
  namespace: '{{ .Release.Namespace }}'