apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skyhook-operator-metrics-reader
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: skyhook-operator
    app.kubernetes.io/part-of: skyhook-operator
  {{- include "chart.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
{{- if .Values.metrics.addServiceAccountBinding }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
  {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics-reader
    app.kubernetes.io/created-by: skyhook-operator
  name: skyhook-operator-metrics-reader-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: skyhook-operator-metrics-reader
subjects:
- kind: ServiceAccount
  name: {{ .Values.metrics.serviceAccountName }}
  namespace: {{ .Values.metrics.serviceAccountNamespace }}
{{- end }}