apiVersion: v1
kind: Service
metadata:
  name: skyhook-operator-controller-manager-metrics-service
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: skyhook-operator
    app.kubernetes.io/part-of: skyhook-operator
    control-plane: controller-manager
  {{- if .Values.metricsService.annotations }}
  annotations:
    {{- .Values.metricsService.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 }}