apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "chart.fullname" . }}-controller-manager-allow-all
  namespace: "{{ .Release.Namespace }}"
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      control-plane: controller-manager
    {{- include "chart.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - {}

