// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package history

import (
	"time"

	"github.com/NVIDIA/nodewright/agent/internal/history"
	"github.com/NVIDIA/nodewright/agent/internal/stage"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Read provides a mock function for the type MockStore
func (_mock *MockStore) Read() (history.Versions, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 history.Versions
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (history.Versions, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() history.Versions); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(history.Versions)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockStore_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
func (_e *MockStore_Expecter) Read() *MockStore_Read_Call {
	return &MockStore_Read_Call{Call: _e.mock.On("Read")}
}

func (_c *MockStore_Read_Call) Run(run func()) *MockStore_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_Read_Call) Return(versions history.Versions, err error) *MockStore_Read_Call {
	_c.Call.Return(versions, err)
	return _c
}

func (_c *MockStore_Read_Call) RunAndReturn(run func() (history.Versions, error)) *MockStore_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Record provides a mock function for the type MockStore
func (_mock *MockStore) Record(completedStage stage.Stage, at time.Time) error {
	ret := _mock.Called(completedStage, at)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(stage.Stage, time.Time) error); ok {
		r0 = returnFunc(completedStage, at)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type MockStore_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - completedStage stage.Stage
//   - at time.Time
func (_e *MockStore_Expecter) Record(completedStage interface{}, at interface{}) *MockStore_Record_Call {
	return &MockStore_Record_Call{Call: _e.mock.On("Record", completedStage, at)}
}

func (_c *MockStore_Record_Call) Run(run func(completedStage stage.Stage, at time.Time)) *MockStore_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 stage.Stage
		if args[0] != nil {
			arg0 = args[0].(stage.Stage)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_Record_Call) Return(err error) *MockStore_Record_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Record_Call) RunAndReturn(run func(completedStage stage.Stage, at time.Time) error) *MockStore_Record_Call {
	_c.Call.Return(run)
	return _c
}
