//go:build !ignore_autogenerated

/*
 * SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatchProcessingState) DeepCopyInto(out *BatchProcessingState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatchProcessingState.
func (in *BatchProcessingState) DeepCopy() *BatchProcessingState {
	if in == nil {
		return nil
	}
	out := new(BatchProcessingState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Compartment) DeepCopyInto(out *Compartment) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	in.Budget.DeepCopyInto(&out.Budget)
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(DeploymentStrategy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Compartment.
func (in *Compartment) DeepCopy() *Compartment {
	if in == nil {
		return nil
	}
	out := new(Compartment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompartmentStatus) DeepCopyInto(out *CompartmentStatus) {
	*out = *in
	if in.BatchState != nil {
		in, out := &in.BatchState, &out.BatchState
		*out = new(BatchProcessingState)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompartmentStatus.
func (in *CompartmentStatus) DeepCopy() *CompartmentStatus {
	if in == nil {
		return nil
	}
	out := new(CompartmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentBudget) DeepCopyInto(out *DeploymentBudget) {
	*out = *in
	if in.Percent != nil {
		in, out := &in.Percent, &out.Percent
		*out = new(int)
		**out = **in
	}
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentBudget.
func (in *DeploymentBudget) DeepCopy() *DeploymentBudget {
	if in == nil {
		return nil
	}
	out := new(DeploymentBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentPolicy) DeepCopyInto(out *DeploymentPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentPolicy.
func (in *DeploymentPolicy) DeepCopy() *DeploymentPolicy {
	if in == nil {
		return nil
	}
	out := new(DeploymentPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeploymentPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentPolicyList) DeepCopyInto(out *DeploymentPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeploymentPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentPolicyList.
func (in *DeploymentPolicyList) DeepCopy() *DeploymentPolicyList {
	if in == nil {
		return nil
	}
	out := new(DeploymentPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeploymentPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentPolicySpec) DeepCopyInto(out *DeploymentPolicySpec) {
	*out = *in
	in.Default.DeepCopyInto(&out.Default)
	if in.Compartments != nil {
		in, out := &in.Compartments, &out.Compartments
		*out = make([]Compartment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentPolicySpec.
func (in *DeploymentPolicySpec) DeepCopy() *DeploymentPolicySpec {
	if in == nil {
		return nil
	}
	out := new(DeploymentPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentPolicyWebhook) DeepCopyInto(out *DeploymentPolicyWebhook) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentPolicyWebhook.
func (in *DeploymentPolicyWebhook) DeepCopy() *DeploymentPolicyWebhook {
	if in == nil {
		return nil
	}
	out := new(DeploymentPolicyWebhook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentStrategy) DeepCopyInto(out *DeploymentStrategy) {
	*out = *in
	if in.Fixed != nil {
		in, out := &in.Fixed, &out.Fixed
		*out = new(FixedStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.Linear != nil {
		in, out := &in.Linear, &out.Linear
		*out = new(LinearStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.Exponential != nil {
		in, out := &in.Exponential, &out.Exponential
		*out = new(ExponentialStrategy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentStrategy.
func (in *DeploymentStrategy) DeepCopy() *DeploymentStrategy {
	if in == nil {
		return nil
	}
	out := new(DeploymentStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExponentialStrategy) DeepCopyInto(out *ExponentialStrategy) {
	*out = *in
	if in.InitialBatch != nil {
		in, out := &in.InitialBatch, &out.InitialBatch
		*out = new(int)
		**out = **in
	}
	if in.GrowthFactor != nil {
		in, out := &in.GrowthFactor, &out.GrowthFactor
		*out = new(int)
		**out = **in
	}
	if in.BatchThreshold != nil {
		in, out := &in.BatchThreshold, &out.BatchThreshold
		*out = new(int)
		**out = **in
	}
	if in.FailureThreshold != nil {
		in, out := &in.FailureThreshold, &out.FailureThreshold
		*out = new(int)
		**out = **in
	}
	if in.SafetyLimit != nil {
		in, out := &in.SafetyLimit, &out.SafetyLimit
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExponentialStrategy.
func (in *ExponentialStrategy) DeepCopy() *ExponentialStrategy {
	if in == nil {
		return nil
	}
	out := new(ExponentialStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FixedStrategy) DeepCopyInto(out *FixedStrategy) {
	*out = *in
	if in.InitialBatch != nil {
		in, out := &in.InitialBatch, &out.InitialBatch
		*out = new(int)
		**out = **in
	}
	if in.BatchThreshold != nil {
		in, out := &in.BatchThreshold, &out.BatchThreshold
		*out = new(int)
		**out = **in
	}
	if in.FailureThreshold != nil {
		in, out := &in.FailureThreshold, &out.FailureThreshold
		*out = new(int)
		**out = **in
	}
	if in.SafetyLimit != nil {
		in, out := &in.SafetyLimit, &out.SafetyLimit
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FixedStrategy.
func (in *FixedStrategy) DeepCopy() *FixedStrategy {
	if in == nil {
		return nil
	}
	out := new(FixedStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Interrupt) DeepCopyInto(out *Interrupt) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Interrupt.
func (in *Interrupt) DeepCopy() *Interrupt {
	if in == nil {
		return nil
	}
	out := new(Interrupt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterruptionBudget) DeepCopyInto(out *InterruptionBudget) {
	*out = *in
	if in.Percent != nil {
		in, out := &in.Percent, &out.Percent
		*out = new(int)
		**out = **in
	}
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterruptionBudget.
func (in *InterruptionBudget) DeepCopy() *InterruptionBudget {
	if in == nil {
		return nil
	}
	out := new(InterruptionBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinearStrategy) DeepCopyInto(out *LinearStrategy) {
	*out = *in
	if in.InitialBatch != nil {
		in, out := &in.InitialBatch, &out.InitialBatch
		*out = new(int)
		**out = **in
	}
	if in.Delta != nil {
		in, out := &in.Delta, &out.Delta
		*out = new(int)
		**out = **in
	}
	if in.BatchThreshold != nil {
		in, out := &in.BatchThreshold, &out.BatchThreshold
		*out = new(int)
		**out = **in
	}
	if in.FailureThreshold != nil {
		in, out := &in.FailureThreshold, &out.FailureThreshold
		*out = new(int)
		**out = **in
	}
	if in.SafetyLimit != nil {
		in, out := &in.SafetyLimit, &out.SafetyLimit
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinearStrategy.
func (in *LinearStrategy) DeepCopy() *LinearStrategy {
	if in == nil {
		return nil
	}
	out := new(LinearStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in NodeState) DeepCopyInto(out *NodeState) {
	{
		in := &in
		*out = make(NodeState, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeState.
func (in NodeState) DeepCopy() NodeState {
	if in == nil {
		return nil
	}
	out := new(NodeState)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Package) DeepCopyInto(out *Package) {
	*out = *in
	out.PackageRef = in.PackageRef
	if in.Interrupt != nil {
		in, out := &in.Interrupt, &out.Interrupt
		*out = new(Interrupt)
		(*in).DeepCopyInto(*out)
	}
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ConfigInterrupts != nil {
		in, out := &in.ConfigInterrupts, &out.ConfigInterrupts
		*out = make(map[string]Interrupt, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ConfigMap != nil {
		in, out := &in.ConfigMap, &out.ConfigMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.GracefulShutdown != nil {
		in, out := &in.GracefulShutdown, &out.GracefulShutdown
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Package.
func (in *Package) DeepCopy() *Package {
	if in == nil {
		return nil
	}
	out := new(Package)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageRef) DeepCopyInto(out *PackageRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageRef.
func (in *PackageRef) DeepCopy() *PackageRef {
	if in == nil {
		return nil
	}
	out := new(PackageRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageStatus) DeepCopyInto(out *PackageStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageStatus.
func (in *PackageStatus) DeepCopy() *PackageStatus {
	if in == nil {
		return nil
	}
	out := new(PackageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Packages) DeepCopyInto(out *Packages) {
	{
		in := &in
		*out = make(Packages, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Packages.
func (in Packages) DeepCopy() Packages {
	if in == nil {
		return nil
	}
	out := new(Packages)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyDefault) DeepCopyInto(out *PolicyDefault) {
	*out = *in
	in.Budget.DeepCopyInto(&out.Budget)
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(DeploymentStrategy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyDefault.
func (in *PolicyDefault) DeepCopy() *PolicyDefault {
	if in == nil {
		return nil
	}
	out := new(PolicyDefault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequirements) DeepCopyInto(out *ResourceRequirements) {
	*out = *in
	out.CPURequest = in.CPURequest.DeepCopy()
	out.CPULimit = in.CPULimit.DeepCopy()
	out.MemoryRequest = in.MemoryRequest.DeepCopy()
	out.MemoryLimit = in.MemoryLimit.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequirements.
func (in *ResourceRequirements) DeepCopy() *ResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Skyhook) DeepCopyInto(out *Skyhook) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Skyhook.
func (in *Skyhook) DeepCopy() *Skyhook {
	if in == nil {
		return nil
	}
	out := new(Skyhook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Skyhook) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkyhookList) DeepCopyInto(out *SkyhookList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Skyhook, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkyhookList.
func (in *SkyhookList) DeepCopy() *SkyhookList {
	if in == nil {
		return nil
	}
	out := new(SkyhookList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SkyhookList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkyhookSpec) DeepCopyInto(out *SkyhookSpec) {
	*out = *in
	in.PodNonInterruptLabels.DeepCopyInto(&out.PodNonInterruptLabels)
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	in.InterruptionBudget.DeepCopyInto(&out.InterruptionBudget)
	if in.Packages != nil {
		in, out := &in.Packages, &out.Packages
		*out = make(Packages, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.AdditionalTolerations != nil {
		in, out := &in.AdditionalTolerations, &out.AdditionalTolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkyhookSpec.
func (in *SkyhookSpec) DeepCopy() *SkyhookSpec {
	if in == nil {
		return nil
	}
	out := new(SkyhookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkyhookStatus) DeepCopyInto(out *SkyhookStatus) {
	*out = *in
	if in.NodeState != nil {
		in, out := &in.NodeState, &out.NodeState
		*out = make(map[string]NodeState, len(*in))
		for key, val := range *in {
			var outVal map[string]PackageStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(NodeState, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.NodeStatus != nil {
		in, out := &in.NodeStatus, &out.NodeStatus
		*out = make(map[string]Status, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeBootIds != nil {
		in, out := &in.NodeBootIds, &out.NodeBootIds
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NodePriority != nil {
		in, out := &in.NodePriority, &out.NodePriority
		*out = make(map[string]metav1.Time, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ConfigUpdates != nil {
		in, out := &in.ConfigUpdates, &out.ConfigUpdates
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.CompartmentStatuses != nil {
		in, out := &in.CompartmentStatuses, &out.CompartmentStatuses
		*out = make(map[string]CompartmentStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkyhookStatus.
func (in *SkyhookStatus) DeepCopy() *SkyhookStatus {
	if in == nil {
		return nil
	}
	out := new(SkyhookStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkyhookWebhook) DeepCopyInto(out *SkyhookWebhook) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkyhookWebhook.
func (in *SkyhookWebhook) DeepCopy() *SkyhookWebhook {
	if in == nil {
		return nil
	}
	out := new(SkyhookWebhook)
	in.DeepCopyInto(out)
	return out
}
