// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interrupts

import (
	"context"

	"github.com/NVIDIA/nodewright/agent/internal/execution"
	"github.com/NVIDIA/nodewright/agent/internal/interrupts"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInterrupt creates a new instance of MockInterrupt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterrupt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterrupt {
	mock := &MockInterrupt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInterrupt is an autogenerated mock type for the Interrupt type
type MockInterrupt struct {
	mock.Mock
}

type MockInterrupt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterrupt) EXPECT() *MockInterrupt_Expecter {
	return &MockInterrupt_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockInterrupt
func (_mock *MockInterrupt) Run(context1 context.Context, config execution.Config) (execution.Status, error) {
	ret := _mock.Called(context1, config)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 execution.Status
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, execution.Config) (execution.Status, error)); ok {
		return returnFunc(context1, config)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, execution.Config) execution.Status); ok {
		r0 = returnFunc(context1, config)
	} else {
		r0 = ret.Get(0).(execution.Status)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, execution.Config) error); ok {
		r1 = returnFunc(context1, config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterrupt_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockInterrupt_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - context1 context.Context
//   - config execution.Config
func (_e *MockInterrupt_Expecter) Run(context1 interface{}, config interface{}) *MockInterrupt_Run_Call {
	return &MockInterrupt_Run_Call{Call: _e.mock.On("Run", context1, config)}
}

func (_c *MockInterrupt_Run_Call) Run(run func(context1 context.Context, config execution.Config)) *MockInterrupt_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 execution.Config
		if args[1] != nil {
			arg1 = args[1].(execution.Config)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInterrupt_Run_Call) Return(status execution.Status, err error) *MockInterrupt_Run_Call {
	_c.Call.Return(status, err)
	return _c
}

func (_c *MockInterrupt_Run_Call) RunAndReturn(run func(context1 context.Context, config execution.Config) (execution.Status, error)) *MockInterrupt_Run_Call {
	_c.Call.Return(run)
	return _c
}

// Serialize provides a mock function for the type MockInterrupt
func (_mock *MockInterrupt) Serialize() ([]byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Serialize")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterrupt_Serialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serialize'
type MockInterrupt_Serialize_Call struct {
	*mock.Call
}

// Serialize is a helper method to define mock.On call
func (_e *MockInterrupt_Expecter) Serialize() *MockInterrupt_Serialize_Call {
	return &MockInterrupt_Serialize_Call{Call: _e.mock.On("Serialize")}
}

func (_c *MockInterrupt_Serialize_Call) Run(run func()) *MockInterrupt_Serialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInterrupt_Serialize_Call) Return(bytes []byte, err error) *MockInterrupt_Serialize_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockInterrupt_Serialize_Call) RunAndReturn(run func() ([]byte, error)) *MockInterrupt_Serialize_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type MockInterrupt
func (_mock *MockInterrupt) Type() interrupts.InterruptType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 interrupts.InterruptType
	if returnFunc, ok := ret.Get(0).(func() interrupts.InterruptType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(interrupts.InterruptType)
	}
	return r0
}

// MockInterrupt_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockInterrupt_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockInterrupt_Expecter) Type() *MockInterrupt_Type_Call {
	return &MockInterrupt_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockInterrupt_Type_Call) Run(run func()) *MockInterrupt_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInterrupt_Type_Call) Return(interruptType interrupts.InterruptType) *MockInterrupt_Type_Call {
	_c.Call.Return(interruptType)
	return _c
}

func (_c *MockInterrupt_Type_Call) RunAndReturn(run func() interrupts.InterruptType) *MockInterrupt_Type_Call {
	_c.Call.Return(run)
	return _c
}
