# 
# LICENSE START
#
#    Copyright (c) NVIDIA CORPORATION.  All rights reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
# LICENSE END
# 







apiVersion: v1
kind: Node
metadata:
  labels:
    skyhook.nvidia.com/test-node: skyhooke2e
  annotations:
    ## the leading test is because it vomits on nil ie empty key, so it must exist and pass the test
    ("skyhook.nvidia.com/nodeState_failure-skyhook" && json_parse("skyhook.nvidia.com/nodeState_failure-skyhook")): 
      {
        "dexter|1.2.3": {
            "name": "dexter",
            "version": "1.2.3",
            "image": "ghcr.io/nvidia/skyhook/agentless",
            "stage": "config",
            "state": "complete"
        },
        "failure|1.2.3": {
            "name": "failure",
            "version": "1.2.3",
            "image": "ghcr.io/nvidia/skyhook/agentless",
            "stage": "apply",
            "state": "erroring",
            (!restarts || restarts == `1`): true
        }
    }
    ## another way to do it
    # (json_parse("skyhook.nvidia.com/nodeState_failure-skyhook")."failure|1.2.3".restarts): 1
    skyhook.nvidia.com/status_failure-skyhook: erroring
status:
  (conditions[?type == 'skyhook.nvidia.com/failure-skyhook/NotReady']):
  - reason: "Incomplete"
    status: "True"
  (conditions[?type == 'skyhook.nvidia.com/failure-skyhook/Erroring']):
  - reason: "Package(s) Erroring or Unknown"
    status: "True"
---
apiVersion: skyhook.nvidia.com/v1alpha1
kind: Skyhook
metadata:
  name: failure-skyhook
status:
  status: erroring
  completeNodes: 0/1
  packageList: "dexter:1.2.3,failure:1.2.3"
  nodesInProgress: 1
# ---
# kind: ConfigMap
# apiVersion: v1
# metadata:
#   namespace: skyhook
#   labels:
#     skyhook.nvidia.com/skyhook-node-meta: failure-skyhook
#   ownerReferences:
#   - apiVersion: skyhook.nvidia.com/v1alpha1
#     blockOwnerDeletion: true
#     controller: true
#     kind: Skyhook
#     name: failure-skyhook
# data:
#   (length(@)): 2
#   labels.json:
#     (contains(@, 'skyhook.nvidia.com/test-node')): true
#     (contains(@, 'skyhook.nvidia.com/status_failure-skyhook')): true
#   annotations.json:
#     (contains(@, 'skyhook.nvidia.com/status_failure-skyhook')): true
#     (contains(@, 'skyhook.nvidia.com/nodeState_failure-skyhook')): true