# 
# LICENSE START
#
#    Copyright (c) NVIDIA CORPORATION.  All rights reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
# LICENSE END
# 







apiVersion: skyhook.nvidia.com/v1alpha1
kind: Skyhook
metadata:
  labels:
    app.kubernetes.io/part-of: skyhook-operator
    app.kubernetes.io/created-by: skyhook-operator
  name: demo
spec:
  nodeSelectors:
    matchLabels:
      eks.amazonaws.com/nodegroup: demo
  interruptionBudget: 
    percent: 100
  podNonInterruptLabels:
    matchLabels:
      app: skyhook-demo-workload
  packages:
    baz:
      version: 2024.8.10
      image: nvcr.io/nvidian/swgpu-baseos/shellscript:1.3.1
      interrupt:
        type: reboot
        # type: service
        # services:
        #   - cron
      configMap:
        config.yaml: |-
          #!/bin/bash
          sleep 100
        config_check.yaml: |-
          #!/bin/bash
          sleep 100