apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels: 
    skyhook.nvidia.com/name: "foobar"
  annotations:
    skyhook.nvidia.com/package: '{"name":"foobar","version":"1.2.3","stage":"apply","skyhook":"foobar"}'
spec:
  restartPolicy: OnFailure
  nodeSelector:
    skyhook.nvidia.com/test-node: skyhooke2e
  initContainers:
  - name: foobar-init
    image: busybox:latest
    command: ["sh", "-c", "sleep 1 && exit"]
  - name: foobar-apply
    image: busybox:latest
    command: ["sh", "-c", "sleep 5 && exit"]
  - name: foobar-applycheck
    image: busybox:latest
    command: ["sh", "-c", "sleep 5 && exit"]
  containers:
  - name: pause
    image: registry.k8s.io/pause:3.10