apiVersion: v1
kind: Node
metadata:
  labels:
    skyhook.nvidia.com/test-node: skyhooke2e
  annotations:
    skyhook.nvidia.com/status_skyhook-upgrade: complete
    skyhook.nvidia.com/version_skyhook-upgrade: v0.5.0
    ("skyhook.nvidia.com/nodeState_skyhook-upgrade" && parse_json("skyhook.nvidia.com/nodeState_skyhook-upgrade")):
      {
        "foobar": { ## assert this bad format exists before migration
            "name": "foobar",
            "version": "1.1",
            "stage": "config",
            "state": "complete"
        },
        "foobar|1.2": {
            "name": "foobar",
            "version": "1.2",
            "image": "ghcr.io/nvidia/skyhook/agentless",
            "stage": "config",
            "state": "complete"
        }
      }
---
apiVersion: v1
kind: Node
metadata:
  labels:
    skyhook.nvidia.com/test-node: skyhooke2e
    skyhook.nvidia.com/status_skyhook-upgrade: complete
  annotations:
    ("skyhook.nvidia.com/nodeState_skyhook-upgrade" && parse_json("skyhook.nvidia.com/nodeState_skyhook-upgrade")):
      {
        "foobar|1.2": {
            "name": "foobar",
            "version": "1.2",
            "image": "ghcr.io/nvidia/skyhook/agentless",
            "stage": "config",
            "state": "complete"
        }
      }
    skyhook.nvidia.com/status_skyhook-upgrade: complete
status:
  (conditions[?type == 'skyhook.nvidia.com/skyhook-upgrade/NotReady']):
  - reason: "Complete"
    status: "False"
  (conditions[?type == 'skyhook.nvidia.com/skyhook-upgrade/Erroring']):
  - reason: "Not Erroring"
    status: "False"
---
apiVersion: skyhook.nvidia.com/v1alpha1
kind: Skyhook
metadata:
  name: skyhook-upgrade
status:
  status: complete
  nodeState:
    (values(@)):
      - foobar|1.2:
          name: foobar
          state: complete
          version: '1.2'
          image: ghcr.io/nvidia/skyhook/agentless
          stage: config
  nodeStatus:
   # grab values should be one and is complete
    (values(@)):
      - complete