# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: skyhook-upgrade
spec:
  skip: true
  timeouts:
    assert: 300s
  steps:
  - try:
    - script:
        content: |
          ## remove annotation from last run
          ../skyhook-cli reset skyhook-upgrade --confirm 2>/dev/null || true
    - script:
        content: |
          ## Set up old format annotation to test migration
          kubectl annotate node --selector=skyhook.nvidia.com/test-node=skyhooke2e \
            skyhook.nvidia.com/nodeState_skyhook-upgrade='{"foobar":{"name":"foobar","version":"1.1","stage":"config","state":"complete"},"foobar|1.2":{"name":"foobar","version":"1.2","image":"ghcr.io/nvidia/skyhook/agentless","stage":"config","state":"complete"}}'\
            skyhook.nvidia.com/status_skyhook-upgrade=complete\
            skyhook.nvidia.com/version_skyhook-upgrade=v0.5.0
    - create:
        file: skyhook.yaml
    - assert:
        file: assert.yaml
