apiVersion: skyhook.nvidia.com/v1alpha1
kind: Skyhook
metadata:
  labels:
    app.kubernetes.io/part-of: skyhook-operator
    app.kubernetes.io/created-by: skyhook-operator
  name: skyhook-upgrade
spec:
  nodeSelectors:
    matchLabels:
      skyhook.nvidia.com/test-node: skyhooke2e
  additionalTolerations:
    - key: nvidia.com/gpu
      effect: NoSchedule
  packages:
    foobar:
      version: "1.2"
      image: ghcr.io/nvidia/skyhook/agentless
      env: 
        - name: SLEEP_LEN
          value: "3" ## making faster so the test works for asserting node condition
      resources:
        cpuLimit: 50m
        cpuRequest: 50m
        memoryLimit: 32Mi
        memoryRequest: 32Mi