# permissions for end users to view skyhooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: skyhook-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: skyhook-operator
    app.kubernetes.io/part-of: skyhook-operator
    app.kubernetes.io/managed-by: kustomize
  name: skyhook-viewer-role
rules:
- apiGroups:
  - skyhook.nvidia.com
  resources:
  - skyhooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - skyhook.nvidia.com
  resources:
  - skyhooks/status
  verbs:
  - get
