# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
kind: Pod
apiVersion: v1
metadata:
  namespace: skyhook
  labels:
    skyhook.nvidia.com/name: interrupt
    skyhook.nvidia.com/package: jason-1.3.2
  annotations:
    ("skyhook.nvidia.com/package" && parse_json("skyhook.nvidia.com/package")):
      {
        "name": "jason",
        "version": "1.3.2",
        "skyhook": "interrupt",
        "stage": "apply",
        "image": "ghcr.io/nvidia/skyhook/agentless"
      }
  ownerReferences:
    - apiVersion: skyhook.nvidia.com/v1alpha1
      kind: Skyhook
      name: interrupt
spec:
  initContainers:
    - name: jason-init
      image: ghcr.io/nvidia/skyhook/agentless:1.3.2
    - name: jason-apply
      image: ghcr.io/nvidia/skyhook/agentless:3.2.3
      args:
        ([0]): apply
        ([1]): /root
        (length(@)): 3
    - name: jason-applycheck
      image: ghcr.io/nvidia/skyhook/agentless:3.2.3
      args:
        ([0]): apply-check
        ([1]): /root
        (length(@)): 3
---
apiVersion: v1
kind: Node
metadata:
  labels:
    skyhook.nvidia.com/test-node: skyhooke2e
    skyhook.nvidia.com/status_interrupt: in_progress
  annotations:
    ("skyhook.nvidia.com/nodeState_interrupt" && parse_json("skyhook.nvidia.com/nodeState_interrupt")):
      {
        "jason|1.3.2": {
            "name": "jason",
            "version": "1.3.2",
            "image": "ghcr.io/nvidia/skyhook/agentless",
            "stage": "config",
            "state": "complete"
        }
      }
    skyhook.nvidia.com/status_interrupt: in_progress
spec:
  taints:
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
status:
  (conditions[?type == 'skyhook.nvidia.com/interrupt/NotReady']):
  - reason: "Incomplete"
    status: "True"
  (conditions[?type == 'skyhook.nvidia.com/interrupt/Erroring']):
  - reason: "Not Erroring"
    status: "False"
---
