# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: legacy-interruption-budget-compatibility
spec:
  description: |
    Tests backwards compatibility with legacy InterruptionBudget.
    - Creates Skyhook with interruptionBudget (count: 3) instead of deploymentPolicy
    - Verifies that a synthetic __default__ compartment is created
    - Verifies that the budget ceiling is respected (max 3 nodes in progress)
    - Ensures existing customers' configurations continue to work
  timeouts:
    exec: 180s
    assert: 120s
  steps:
  - name: setup-nodes
    try:
    - script:
        content: |
          chmod +x setup-nodes.sh cleanup-nodes.sh
          ./setup-nodes.sh

  - name: apply-skyhook
    try:
    - apply:
        file: skyhook.yaml
    - script:
        content: |
          echo "Waiting for Skyhook to initialize..."
          sleep 10

  - name: verify-default-compartment-created
    try:
    - script:
        content: |
          echo "=== Verifying synthetic __default__ compartment ==="
          
          COMPARTMENTS=$(kubectl get skyhook legacy-interruption-budget-test -o jsonpath='{.status.compartmentStatuses}' | jq -r 'keys[]')
          echo "Compartments found: $COMPARTMENTS"
          
          DEFAULT=$(echo "$COMPARTMENTS" | grep -c "__default__" || echo "0")
          
          if [ "$DEFAULT" != "1" ]; then
            echo "ERROR: Expected __default__ compartment to be created"
            echo "Found compartments: $COMPARTMENTS"
            kubectl get skyhook legacy-interruption-budget-test -o yaml
            exit 1
          fi
          
          echo "✓ Synthetic __default__ compartment created"

  - name: verify-compartment-uses-fixed-strategy
    try:
    - script:
        content: |
          echo "=== Verifying FixedStrategy is used ==="
          
          # Get the compartment details from status
          MATCHED=$(kubectl get skyhook legacy-interruption-budget-test \
            -o jsonpath='{.status.compartmentStatuses.__default__.matched}')
          
          echo "Nodes matched: $MATCHED (expected: 6)"
          
          if [ "$MATCHED" != "6" ]; then
            echo "ERROR: Expected 6 nodes in default compartment, got $MATCHED"
            kubectl get skyhook legacy-interruption-budget-test -o yaml
            exit 1
          fi
          
          echo "✓ All nodes assigned to __default__ compartment"

  - name: verify-budget-ceiling-configured
    try:
    - script:
        content: |
          echo "=== Verifying budget ceiling is configured ==="
          
          CEILING=$(kubectl get skyhook legacy-interruption-budget-test \
            -o jsonpath='{.status.compartmentStatuses.__default__.ceiling}')
          
          echo "Configured ceiling: $CEILING (expected: 3)"
          
          if [ "$CEILING" != "3" ]; then
            echo "ERROR: Expected ceiling of 3 (from interruptionBudget count), got $CEILING"
            kubectl get skyhook legacy-interruption-budget-test -o yaml
            exit 1
          fi
          
          echo "✓ Budget ceiling configured correctly from InterruptionBudget"

  - name: verify-final-state
    try:
    - script:
        content: |
          echo "=== Verifying legacy compatibility ==="
          
          CEILING=$(kubectl get skyhook legacy-interruption-budget-test -o jsonpath='{.status.compartmentStatuses.__default__.ceiling}')
          MATCHED=$(kubectl get skyhook legacy-interruption-budget-test -o jsonpath='{.status.compartmentStatuses.__default__.matched}')
          
          echo "Final verification:"
          echo "  - Synthetic __default__ compartment: ✓"
          echo "  - Budget ceiling from interruptionBudget: $CEILING"
          echo "  - Matched nodes: $MATCHED"
          
          if [ "$CEILING" != "3" ] || [ "$MATCHED" != "6" ]; then
            echo "ERROR: Legacy compatibility verification failed"
            exit 1
          fi
          
          echo ""
          echo "✓✓✓ Legacy InterruptionBudget compatibility verified! ✓✓✓"
          echo "Existing customers can continue using interruptionBudget safely."
    - script:
        content: |
          echo "=== Verifying legacy compatibility metrics ==="
          
          # Verify metrics for synthetic __default__ compartment
          ../metrics_test.py skyhook_rollout_matched_nodes 6 -t skyhook_name=legacy-interruption-budget-test -t policy_name=legacy -t compartment_name=__default__ -t strategy=fixed
          ../metrics_test.py skyhook_rollout_ceiling 3 -t skyhook_name=legacy-interruption-budget-test -t policy_name=legacy -t compartment_name=__default__ -t strategy=fixed
          
          # Verify that the legacy policy name is "legacy" and not a real policy
          echo "✓ Legacy compatibility metrics verified!"
          echo "✓ Metrics use policy_name=legacy for backwards compatibility"

  - name: cleanup
    try:
    - script:
        content: |
          ./cleanup-nodes.sh || true
