/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package wrapper

import (
	"github.com/NVIDIA/skyhook/operator/api/v1alpha1"
	"github.com/NVIDIA/skyhook/operator/internal/wrapper"
	"github.com/go-logr/logr"
	mock "github.com/stretchr/testify/mock"
	"k8s.io/api/core/v1"
)

// NewMockSkyhookNode creates a new instance of MockSkyhookNode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSkyhookNode(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSkyhookNode {
	mock := &MockSkyhookNode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSkyhookNode is an autogenerated mock type for the SkyhookNode type
type MockSkyhookNode struct {
	mock.Mock
}

type MockSkyhookNode_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSkyhookNode) EXPECT() *MockSkyhookNode_Expecter {
	return &MockSkyhookNode_Expecter{mock: &_m.Mock}
}

// Changed provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) Changed() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Changed")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockSkyhookNode_Changed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Changed'
type MockSkyhookNode_Changed_Call struct {
	*mock.Call
}

// Changed is a helper method to define mock.On call
func (_e *MockSkyhookNode_Expecter) Changed() *MockSkyhookNode_Changed_Call {
	return &MockSkyhookNode_Changed_Call{Call: _e.mock.On("Changed")}
}

func (_c *MockSkyhookNode_Changed_Call) Run(run func()) *MockSkyhookNode_Changed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNode_Changed_Call) Return(b bool) *MockSkyhookNode_Changed_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockSkyhookNode_Changed_Call) RunAndReturn(run func() bool) *MockSkyhookNode_Changed_Call {
	_c.Call.Return(run)
	return _c
}

// Cordon provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) Cordon() {
	_mock.Called()
	return
}

// MockSkyhookNode_Cordon_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cordon'
type MockSkyhookNode_Cordon_Call struct {
	*mock.Call
}

// Cordon is a helper method to define mock.On call
func (_e *MockSkyhookNode_Expecter) Cordon() *MockSkyhookNode_Cordon_Call {
	return &MockSkyhookNode_Cordon_Call{Call: _e.mock.On("Cordon")}
}

func (_c *MockSkyhookNode_Cordon_Call) Run(run func()) *MockSkyhookNode_Cordon_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNode_Cordon_Call) Return() *MockSkyhookNode_Cordon_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSkyhookNode_Cordon_Call) RunAndReturn(run func()) *MockSkyhookNode_Cordon_Call {
	_c.Run(run)
	return _c
}

// GetComplete provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) GetComplete() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetComplete")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockSkyhookNode_GetComplete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComplete'
type MockSkyhookNode_GetComplete_Call struct {
	*mock.Call
}

// GetComplete is a helper method to define mock.On call
func (_e *MockSkyhookNode_Expecter) GetComplete() *MockSkyhookNode_GetComplete_Call {
	return &MockSkyhookNode_GetComplete_Call{Call: _e.mock.On("GetComplete")}
}

func (_c *MockSkyhookNode_GetComplete_Call) Run(run func()) *MockSkyhookNode_GetComplete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNode_GetComplete_Call) Return(strings []string) *MockSkyhookNode_GetComplete_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockSkyhookNode_GetComplete_Call) RunAndReturn(run func() []string) *MockSkyhookNode_GetComplete_Call {
	_c.Call.Return(run)
	return _c
}

// GetNode provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) GetNode() *v1.Node {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNode")
	}

	var r0 *v1.Node
	if returnFunc, ok := ret.Get(0).(func() *v1.Node); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Node)
		}
	}
	return r0
}

// MockSkyhookNode_GetNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNode'
type MockSkyhookNode_GetNode_Call struct {
	*mock.Call
}

// GetNode is a helper method to define mock.On call
func (_e *MockSkyhookNode_Expecter) GetNode() *MockSkyhookNode_GetNode_Call {
	return &MockSkyhookNode_GetNode_Call{Call: _e.mock.On("GetNode")}
}

func (_c *MockSkyhookNode_GetNode_Call) Run(run func()) *MockSkyhookNode_GetNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNode_GetNode_Call) Return(node *v1.Node) *MockSkyhookNode_GetNode_Call {
	_c.Call.Return(node)
	return _c
}

func (_c *MockSkyhookNode_GetNode_Call) RunAndReturn(run func() *v1.Node) *MockSkyhookNode_GetNode_Call {
	_c.Call.Return(run)
	return _c
}

// GetSkyhook provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) GetSkyhook() *wrapper.Skyhook {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSkyhook")
	}

	var r0 *wrapper.Skyhook
	if returnFunc, ok := ret.Get(0).(func() *wrapper.Skyhook); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wrapper.Skyhook)
		}
	}
	return r0
}

// MockSkyhookNode_GetSkyhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSkyhook'
type MockSkyhookNode_GetSkyhook_Call struct {
	*mock.Call
}

// GetSkyhook is a helper method to define mock.On call
func (_e *MockSkyhookNode_Expecter) GetSkyhook() *MockSkyhookNode_GetSkyhook_Call {
	return &MockSkyhookNode_GetSkyhook_Call{Call: _e.mock.On("GetSkyhook")}
}

func (_c *MockSkyhookNode_GetSkyhook_Call) Run(run func()) *MockSkyhookNode_GetSkyhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNode_GetSkyhook_Call) Return(skyhook *wrapper.Skyhook) *MockSkyhookNode_GetSkyhook_Call {
	_c.Call.Return(skyhook)
	return _c
}

func (_c *MockSkyhookNode_GetSkyhook_Call) RunAndReturn(run func() *wrapper.Skyhook) *MockSkyhookNode_GetSkyhook_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) GetVersion() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSkyhookNode_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type MockSkyhookNode_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
func (_e *MockSkyhookNode_Expecter) GetVersion() *MockSkyhookNode_GetVersion_Call {
	return &MockSkyhookNode_GetVersion_Call{Call: _e.mock.On("GetVersion")}
}

func (_c *MockSkyhookNode_GetVersion_Call) Run(run func()) *MockSkyhookNode_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNode_GetVersion_Call) Return(s string) *MockSkyhookNode_GetVersion_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSkyhookNode_GetVersion_Call) RunAndReturn(run func() string) *MockSkyhookNode_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}

// HasInterrupt provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) HasInterrupt(_package v1alpha1.Package) bool {
	ret := _mock.Called(_package)

	if len(ret) == 0 {
		panic("no return value specified for HasInterrupt")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(v1alpha1.Package) bool); ok {
		r0 = returnFunc(_package)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockSkyhookNode_HasInterrupt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasInterrupt'
type MockSkyhookNode_HasInterrupt_Call struct {
	*mock.Call
}

// HasInterrupt is a helper method to define mock.On call
//   - _package v1alpha1.Package
func (_e *MockSkyhookNode_Expecter) HasInterrupt(_package interface{}) *MockSkyhookNode_HasInterrupt_Call {
	return &MockSkyhookNode_HasInterrupt_Call{Call: _e.mock.On("HasInterrupt", _package)}
}

func (_c *MockSkyhookNode_HasInterrupt_Call) Run(run func(_package v1alpha1.Package)) *MockSkyhookNode_HasInterrupt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 v1alpha1.Package
		if args[0] != nil {
			arg0 = args[0].(v1alpha1.Package)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSkyhookNode_HasInterrupt_Call) Return(b bool) *MockSkyhookNode_HasInterrupt_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockSkyhookNode_HasInterrupt_Call) RunAndReturn(run func(_package v1alpha1.Package) bool) *MockSkyhookNode_HasInterrupt_Call {
	_c.Call.Return(run)
	return _c
}

// IsComplete provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) IsComplete() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsComplete")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockSkyhookNode_IsComplete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsComplete'
type MockSkyhookNode_IsComplete_Call struct {
	*mock.Call
}

// IsComplete is a helper method to define mock.On call
func (_e *MockSkyhookNode_Expecter) IsComplete() *MockSkyhookNode_IsComplete_Call {
	return &MockSkyhookNode_IsComplete_Call{Call: _e.mock.On("IsComplete")}
}

func (_c *MockSkyhookNode_IsComplete_Call) Run(run func()) *MockSkyhookNode_IsComplete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNode_IsComplete_Call) Return(b bool) *MockSkyhookNode_IsComplete_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockSkyhookNode_IsComplete_Call) RunAndReturn(run func() bool) *MockSkyhookNode_IsComplete_Call {
	_c.Call.Return(run)
	return _c
}

// IsPackageComplete provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) IsPackageComplete(_package v1alpha1.Package) bool {
	ret := _mock.Called(_package)

	if len(ret) == 0 {
		panic("no return value specified for IsPackageComplete")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(v1alpha1.Package) bool); ok {
		r0 = returnFunc(_package)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockSkyhookNode_IsPackageComplete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsPackageComplete'
type MockSkyhookNode_IsPackageComplete_Call struct {
	*mock.Call
}

// IsPackageComplete is a helper method to define mock.On call
//   - _package v1alpha1.Package
func (_e *MockSkyhookNode_Expecter) IsPackageComplete(_package interface{}) *MockSkyhookNode_IsPackageComplete_Call {
	return &MockSkyhookNode_IsPackageComplete_Call{Call: _e.mock.On("IsPackageComplete", _package)}
}

func (_c *MockSkyhookNode_IsPackageComplete_Call) Run(run func(_package v1alpha1.Package)) *MockSkyhookNode_IsPackageComplete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 v1alpha1.Package
		if args[0] != nil {
			arg0 = args[0].(v1alpha1.Package)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSkyhookNode_IsPackageComplete_Call) Return(b bool) *MockSkyhookNode_IsPackageComplete_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockSkyhookNode_IsPackageComplete_Call) RunAndReturn(run func(_package v1alpha1.Package) bool) *MockSkyhookNode_IsPackageComplete_Call {
	_c.Call.Return(run)
	return _c
}

// Migrate provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) Migrate(logger logr.Logger) error {
	ret := _mock.Called(logger)

	if len(ret) == 0 {
		panic("no return value specified for Migrate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(logr.Logger) error); ok {
		r0 = returnFunc(logger)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSkyhookNode_Migrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migrate'
type MockSkyhookNode_Migrate_Call struct {
	*mock.Call
}

// Migrate is a helper method to define mock.On call
//   - logger logr.Logger
func (_e *MockSkyhookNode_Expecter) Migrate(logger interface{}) *MockSkyhookNode_Migrate_Call {
	return &MockSkyhookNode_Migrate_Call{Call: _e.mock.On("Migrate", logger)}
}

func (_c *MockSkyhookNode_Migrate_Call) Run(run func(logger logr.Logger)) *MockSkyhookNode_Migrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 logr.Logger
		if args[0] != nil {
			arg0 = args[0].(logr.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSkyhookNode_Migrate_Call) Return(err error) *MockSkyhookNode_Migrate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSkyhookNode_Migrate_Call) RunAndReturn(run func(logger logr.Logger) error) *MockSkyhookNode_Migrate_Call {
	_c.Call.Return(run)
	return _c
}

// NextStage provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) NextStage(_package *v1alpha1.Package) *v1alpha1.Stage {
	ret := _mock.Called(_package)

	if len(ret) == 0 {
		panic("no return value specified for NextStage")
	}

	var r0 *v1alpha1.Stage
	if returnFunc, ok := ret.Get(0).(func(*v1alpha1.Package) *v1alpha1.Stage); ok {
		r0 = returnFunc(_package)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Stage)
		}
	}
	return r0
}

// MockSkyhookNode_NextStage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextStage'
type MockSkyhookNode_NextStage_Call struct {
	*mock.Call
}

// NextStage is a helper method to define mock.On call
//   - _package *v1alpha1.Package
func (_e *MockSkyhookNode_Expecter) NextStage(_package interface{}) *MockSkyhookNode_NextStage_Call {
	return &MockSkyhookNode_NextStage_Call{Call: _e.mock.On("NextStage", _package)}
}

func (_c *MockSkyhookNode_NextStage_Call) Run(run func(_package *v1alpha1.Package)) *MockSkyhookNode_NextStage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *v1alpha1.Package
		if args[0] != nil {
			arg0 = args[0].(*v1alpha1.Package)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSkyhookNode_NextStage_Call) Return(stage *v1alpha1.Stage) *MockSkyhookNode_NextStage_Call {
	_c.Call.Return(stage)
	return _c
}

func (_c *MockSkyhookNode_NextStage_Call) RunAndReturn(run func(_package *v1alpha1.Package) *v1alpha1.Stage) *MockSkyhookNode_NextStage_Call {
	_c.Call.Return(run)
	return _c
}

// PackageStatus provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) PackageStatus(name string) (*v1alpha1.PackageStatus, bool) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for PackageStatus")
	}

	var r0 *v1alpha1.PackageStatus
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (*v1alpha1.PackageStatus, bool)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *v1alpha1.PackageStatus); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.PackageStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockSkyhookNode_PackageStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PackageStatus'
type MockSkyhookNode_PackageStatus_Call struct {
	*mock.Call
}

// PackageStatus is a helper method to define mock.On call
//   - name string
func (_e *MockSkyhookNode_Expecter) PackageStatus(name interface{}) *MockSkyhookNode_PackageStatus_Call {
	return &MockSkyhookNode_PackageStatus_Call{Call: _e.mock.On("PackageStatus", name)}
}

func (_c *MockSkyhookNode_PackageStatus_Call) Run(run func(name string)) *MockSkyhookNode_PackageStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSkyhookNode_PackageStatus_Call) Return(packageStatus *v1alpha1.PackageStatus, b bool) *MockSkyhookNode_PackageStatus_Call {
	_c.Call.Return(packageStatus, b)
	return _c
}

func (_c *MockSkyhookNode_PackageStatus_Call) RunAndReturn(run func(name string) (*v1alpha1.PackageStatus, bool)) *MockSkyhookNode_PackageStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ProgressSkipped provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) ProgressSkipped() {
	_mock.Called()
	return
}

// MockSkyhookNode_ProgressSkipped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProgressSkipped'
type MockSkyhookNode_ProgressSkipped_Call struct {
	*mock.Call
}

// ProgressSkipped is a helper method to define mock.On call
func (_e *MockSkyhookNode_Expecter) ProgressSkipped() *MockSkyhookNode_ProgressSkipped_Call {
	return &MockSkyhookNode_ProgressSkipped_Call{Call: _e.mock.On("ProgressSkipped")}
}

func (_c *MockSkyhookNode_ProgressSkipped_Call) Run(run func()) *MockSkyhookNode_ProgressSkipped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNode_ProgressSkipped_Call) Return() *MockSkyhookNode_ProgressSkipped_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSkyhookNode_ProgressSkipped_Call) RunAndReturn(run func()) *MockSkyhookNode_ProgressSkipped_Call {
	_c.Run(run)
	return _c
}

// RemoveState provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) RemoveState(_package v1alpha1.PackageRef) error {
	ret := _mock.Called(_package)

	if len(ret) == 0 {
		panic("no return value specified for RemoveState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(v1alpha1.PackageRef) error); ok {
		r0 = returnFunc(_package)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSkyhookNode_RemoveState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveState'
type MockSkyhookNode_RemoveState_Call struct {
	*mock.Call
}

// RemoveState is a helper method to define mock.On call
//   - _package v1alpha1.PackageRef
func (_e *MockSkyhookNode_Expecter) RemoveState(_package interface{}) *MockSkyhookNode_RemoveState_Call {
	return &MockSkyhookNode_RemoveState_Call{Call: _e.mock.On("RemoveState", _package)}
}

func (_c *MockSkyhookNode_RemoveState_Call) Run(run func(_package v1alpha1.PackageRef)) *MockSkyhookNode_RemoveState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 v1alpha1.PackageRef
		if args[0] != nil {
			arg0 = args[0].(v1alpha1.PackageRef)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSkyhookNode_RemoveState_Call) Return(err error) *MockSkyhookNode_RemoveState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSkyhookNode_RemoveState_Call) RunAndReturn(run func(_package v1alpha1.PackageRef) error) *MockSkyhookNode_RemoveState_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTaint provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) RemoveTaint(key string) {
	_mock.Called(key)
	return
}

// MockSkyhookNode_RemoveTaint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTaint'
type MockSkyhookNode_RemoveTaint_Call struct {
	*mock.Call
}

// RemoveTaint is a helper method to define mock.On call
//   - key string
func (_e *MockSkyhookNode_Expecter) RemoveTaint(key interface{}) *MockSkyhookNode_RemoveTaint_Call {
	return &MockSkyhookNode_RemoveTaint_Call{Call: _e.mock.On("RemoveTaint", key)}
}

func (_c *MockSkyhookNode_RemoveTaint_Call) Run(run func(key string)) *MockSkyhookNode_RemoveTaint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSkyhookNode_RemoveTaint_Call) Return() *MockSkyhookNode_RemoveTaint_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSkyhookNode_RemoveTaint_Call) RunAndReturn(run func(key string)) *MockSkyhookNode_RemoveTaint_Call {
	_c.Run(run)
	return _c
}

// Reset provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) Reset() {
	_mock.Called()
	return
}

// MockSkyhookNode_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type MockSkyhookNode_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
func (_e *MockSkyhookNode_Expecter) Reset() *MockSkyhookNode_Reset_Call {
	return &MockSkyhookNode_Reset_Call{Call: _e.mock.On("Reset")}
}

func (_c *MockSkyhookNode_Reset_Call) Run(run func()) *MockSkyhookNode_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNode_Reset_Call) Return() *MockSkyhookNode_Reset_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSkyhookNode_Reset_Call) RunAndReturn(run func()) *MockSkyhookNode_Reset_Call {
	_c.Run(run)
	return _c
}

// RunNext provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) RunNext() ([]*v1alpha1.Package, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RunNext")
	}

	var r0 []*v1alpha1.Package
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*v1alpha1.Package, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*v1alpha1.Package); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1alpha1.Package)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSkyhookNode_RunNext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunNext'
type MockSkyhookNode_RunNext_Call struct {
	*mock.Call
}

// RunNext is a helper method to define mock.On call
func (_e *MockSkyhookNode_Expecter) RunNext() *MockSkyhookNode_RunNext_Call {
	return &MockSkyhookNode_RunNext_Call{Call: _e.mock.On("RunNext")}
}

func (_c *MockSkyhookNode_RunNext_Call) Run(run func()) *MockSkyhookNode_RunNext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNode_RunNext_Call) Return(packages []*v1alpha1.Package, err error) *MockSkyhookNode_RunNext_Call {
	_c.Call.Return(packages, err)
	return _c
}

func (_c *MockSkyhookNode_RunNext_Call) RunAndReturn(run func() ([]*v1alpha1.Package, error)) *MockSkyhookNode_RunNext_Call {
	_c.Call.Return(run)
	return _c
}

// SetState provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) SetState(state v1alpha1.NodeState) error {
	ret := _mock.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for SetState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(v1alpha1.NodeState) error); ok {
		r0 = returnFunc(state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSkyhookNode_SetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetState'
type MockSkyhookNode_SetState_Call struct {
	*mock.Call
}

// SetState is a helper method to define mock.On call
//   - state v1alpha1.NodeState
func (_e *MockSkyhookNode_Expecter) SetState(state interface{}) *MockSkyhookNode_SetState_Call {
	return &MockSkyhookNode_SetState_Call{Call: _e.mock.On("SetState", state)}
}

func (_c *MockSkyhookNode_SetState_Call) Run(run func(state v1alpha1.NodeState)) *MockSkyhookNode_SetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 v1alpha1.NodeState
		if args[0] != nil {
			arg0 = args[0].(v1alpha1.NodeState)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSkyhookNode_SetState_Call) Return(err error) *MockSkyhookNode_SetState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSkyhookNode_SetState_Call) RunAndReturn(run func(state v1alpha1.NodeState) error) *MockSkyhookNode_SetState_Call {
	_c.Call.Return(run)
	return _c
}

// SetStatus provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) SetStatus(status v1alpha1.Status) {
	_mock.Called(status)
	return
}

// MockSkyhookNode_SetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatus'
type MockSkyhookNode_SetStatus_Call struct {
	*mock.Call
}

// SetStatus is a helper method to define mock.On call
//   - status v1alpha1.Status
func (_e *MockSkyhookNode_Expecter) SetStatus(status interface{}) *MockSkyhookNode_SetStatus_Call {
	return &MockSkyhookNode_SetStatus_Call{Call: _e.mock.On("SetStatus", status)}
}

func (_c *MockSkyhookNode_SetStatus_Call) Run(run func(status v1alpha1.Status)) *MockSkyhookNode_SetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 v1alpha1.Status
		if args[0] != nil {
			arg0 = args[0].(v1alpha1.Status)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSkyhookNode_SetStatus_Call) Return() *MockSkyhookNode_SetStatus_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSkyhookNode_SetStatus_Call) RunAndReturn(run func(status v1alpha1.Status)) *MockSkyhookNode_SetStatus_Call {
	_c.Run(run)
	return _c
}

// SetVersion provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) SetVersion() {
	_mock.Called()
	return
}

// MockSkyhookNode_SetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVersion'
type MockSkyhookNode_SetVersion_Call struct {
	*mock.Call
}

// SetVersion is a helper method to define mock.On call
func (_e *MockSkyhookNode_Expecter) SetVersion() *MockSkyhookNode_SetVersion_Call {
	return &MockSkyhookNode_SetVersion_Call{Call: _e.mock.On("SetVersion")}
}

func (_c *MockSkyhookNode_SetVersion_Call) Run(run func()) *MockSkyhookNode_SetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNode_SetVersion_Call) Return() *MockSkyhookNode_SetVersion_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSkyhookNode_SetVersion_Call) RunAndReturn(run func()) *MockSkyhookNode_SetVersion_Call {
	_c.Run(run)
	return _c
}

// State provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) State() (v1alpha1.NodeState, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 v1alpha1.NodeState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (v1alpha1.NodeState, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() v1alpha1.NodeState); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.NodeState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSkyhookNode_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type MockSkyhookNode_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
func (_e *MockSkyhookNode_Expecter) State() *MockSkyhookNode_State_Call {
	return &MockSkyhookNode_State_Call{Call: _e.mock.On("State")}
}

func (_c *MockSkyhookNode_State_Call) Run(run func()) *MockSkyhookNode_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNode_State_Call) Return(nodeState v1alpha1.NodeState, err error) *MockSkyhookNode_State_Call {
	_c.Call.Return(nodeState, err)
	return _c
}

func (_c *MockSkyhookNode_State_Call) RunAndReturn(run func() (v1alpha1.NodeState, error)) *MockSkyhookNode_State_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) Status() v1alpha1.Status {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 v1alpha1.Status
	if returnFunc, ok := ret.Get(0).(func() v1alpha1.Status); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(v1alpha1.Status)
	}
	return r0
}

// MockSkyhookNode_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockSkyhookNode_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *MockSkyhookNode_Expecter) Status() *MockSkyhookNode_Status_Call {
	return &MockSkyhookNode_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *MockSkyhookNode_Status_Call) Run(run func()) *MockSkyhookNode_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNode_Status_Call) Return(status v1alpha1.Status) *MockSkyhookNode_Status_Call {
	_c.Call.Return(status)
	return _c
}

func (_c *MockSkyhookNode_Status_Call) RunAndReturn(run func() v1alpha1.Status) *MockSkyhookNode_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Taint provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) Taint(key string) {
	_mock.Called(key)
	return
}

// MockSkyhookNode_Taint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Taint'
type MockSkyhookNode_Taint_Call struct {
	*mock.Call
}

// Taint is a helper method to define mock.On call
//   - key string
func (_e *MockSkyhookNode_Expecter) Taint(key interface{}) *MockSkyhookNode_Taint_Call {
	return &MockSkyhookNode_Taint_Call{Call: _e.mock.On("Taint", key)}
}

func (_c *MockSkyhookNode_Taint_Call) Run(run func(key string)) *MockSkyhookNode_Taint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSkyhookNode_Taint_Call) Return() *MockSkyhookNode_Taint_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSkyhookNode_Taint_Call) RunAndReturn(run func(key string)) *MockSkyhookNode_Taint_Call {
	_c.Run(run)
	return _c
}

// Uncordon provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) Uncordon() {
	_mock.Called()
	return
}

// MockSkyhookNode_Uncordon_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Uncordon'
type MockSkyhookNode_Uncordon_Call struct {
	*mock.Call
}

// Uncordon is a helper method to define mock.On call
func (_e *MockSkyhookNode_Expecter) Uncordon() *MockSkyhookNode_Uncordon_Call {
	return &MockSkyhookNode_Uncordon_Call{Call: _e.mock.On("Uncordon")}
}

func (_c *MockSkyhookNode_Uncordon_Call) Run(run func()) *MockSkyhookNode_Uncordon_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNode_Uncordon_Call) Return() *MockSkyhookNode_Uncordon_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSkyhookNode_Uncordon_Call) RunAndReturn(run func()) *MockSkyhookNode_Uncordon_Call {
	_c.Run(run)
	return _c
}

// UpdateCondition provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) UpdateCondition() {
	_mock.Called()
	return
}

// MockSkyhookNode_UpdateCondition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCondition'
type MockSkyhookNode_UpdateCondition_Call struct {
	*mock.Call
}

// UpdateCondition is a helper method to define mock.On call
func (_e *MockSkyhookNode_Expecter) UpdateCondition() *MockSkyhookNode_UpdateCondition_Call {
	return &MockSkyhookNode_UpdateCondition_Call{Call: _e.mock.On("UpdateCondition")}
}

func (_c *MockSkyhookNode_UpdateCondition_Call) Run(run func()) *MockSkyhookNode_UpdateCondition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNode_UpdateCondition_Call) Return() *MockSkyhookNode_UpdateCondition_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSkyhookNode_UpdateCondition_Call) RunAndReturn(run func()) *MockSkyhookNode_UpdateCondition_Call {
	_c.Run(run)
	return _c
}

// Upsert provides a mock function for the type MockSkyhookNode
func (_mock *MockSkyhookNode) Upsert(_package v1alpha1.PackageRef, image string, state v1alpha1.State, stage v1alpha1.Stage, restarts int32, containerSHA string) error {
	ret := _mock.Called(_package, image, state, stage, restarts, containerSHA)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(v1alpha1.PackageRef, string, v1alpha1.State, v1alpha1.Stage, int32, string) error); ok {
		r0 = returnFunc(_package, image, state, stage, restarts, containerSHA)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSkyhookNode_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockSkyhookNode_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - _package v1alpha1.PackageRef
//   - image string
//   - state v1alpha1.State
//   - stage v1alpha1.Stage
//   - restarts int32
//   - containerSHA string
func (_e *MockSkyhookNode_Expecter) Upsert(_package interface{}, image interface{}, state interface{}, stage interface{}, restarts interface{}, containerSHA interface{}) *MockSkyhookNode_Upsert_Call {
	return &MockSkyhookNode_Upsert_Call{Call: _e.mock.On("Upsert", _package, image, state, stage, restarts, containerSHA)}
}

func (_c *MockSkyhookNode_Upsert_Call) Run(run func(_package v1alpha1.PackageRef, image string, state v1alpha1.State, stage v1alpha1.Stage, restarts int32, containerSHA string)) *MockSkyhookNode_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 v1alpha1.PackageRef
		if args[0] != nil {
			arg0 = args[0].(v1alpha1.PackageRef)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 v1alpha1.State
		if args[2] != nil {
			arg2 = args[2].(v1alpha1.State)
		}
		var arg3 v1alpha1.Stage
		if args[3] != nil {
			arg3 = args[3].(v1alpha1.Stage)
		}
		var arg4 int32
		if args[4] != nil {
			arg4 = args[4].(int32)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockSkyhookNode_Upsert_Call) Return(err error) *MockSkyhookNode_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSkyhookNode_Upsert_Call) RunAndReturn(run func(_package v1alpha1.PackageRef, image string, state v1alpha1.State, stage v1alpha1.Stage, restarts int32, containerSHA string) error) *MockSkyhookNode_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
