/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package wrapper

import (
	"github.com/NVIDIA/skyhook/operator/api/v1alpha1"
	"github.com/go-logr/logr"
	mock "github.com/stretchr/testify/mock"
	"k8s.io/api/core/v1"
)

// NewMockSkyhookNodeOnly creates a new instance of MockSkyhookNodeOnly. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSkyhookNodeOnly(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSkyhookNodeOnly {
	mock := &MockSkyhookNodeOnly{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSkyhookNodeOnly is an autogenerated mock type for the SkyhookNodeOnly type
type MockSkyhookNodeOnly struct {
	mock.Mock
}

type MockSkyhookNodeOnly_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSkyhookNodeOnly) EXPECT() *MockSkyhookNodeOnly_Expecter {
	return &MockSkyhookNodeOnly_Expecter{mock: &_m.Mock}
}

// Changed provides a mock function for the type MockSkyhookNodeOnly
func (_mock *MockSkyhookNodeOnly) Changed() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Changed")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockSkyhookNodeOnly_Changed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Changed'
type MockSkyhookNodeOnly_Changed_Call struct {
	*mock.Call
}

// Changed is a helper method to define mock.On call
func (_e *MockSkyhookNodeOnly_Expecter) Changed() *MockSkyhookNodeOnly_Changed_Call {
	return &MockSkyhookNodeOnly_Changed_Call{Call: _e.mock.On("Changed")}
}

func (_c *MockSkyhookNodeOnly_Changed_Call) Run(run func()) *MockSkyhookNodeOnly_Changed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNodeOnly_Changed_Call) Return(b bool) *MockSkyhookNodeOnly_Changed_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockSkyhookNodeOnly_Changed_Call) RunAndReturn(run func() bool) *MockSkyhookNodeOnly_Changed_Call {
	_c.Call.Return(run)
	return _c
}

// Cordon provides a mock function for the type MockSkyhookNodeOnly
func (_mock *MockSkyhookNodeOnly) Cordon() {
	_mock.Called()
	return
}

// MockSkyhookNodeOnly_Cordon_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cordon'
type MockSkyhookNodeOnly_Cordon_Call struct {
	*mock.Call
}

// Cordon is a helper method to define mock.On call
func (_e *MockSkyhookNodeOnly_Expecter) Cordon() *MockSkyhookNodeOnly_Cordon_Call {
	return &MockSkyhookNodeOnly_Cordon_Call{Call: _e.mock.On("Cordon")}
}

func (_c *MockSkyhookNodeOnly_Cordon_Call) Run(run func()) *MockSkyhookNodeOnly_Cordon_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNodeOnly_Cordon_Call) Return() *MockSkyhookNodeOnly_Cordon_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSkyhookNodeOnly_Cordon_Call) RunAndReturn(run func()) *MockSkyhookNodeOnly_Cordon_Call {
	_c.Run(run)
	return _c
}

// GetNode provides a mock function for the type MockSkyhookNodeOnly
func (_mock *MockSkyhookNodeOnly) GetNode() *v1.Node {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNode")
	}

	var r0 *v1.Node
	if returnFunc, ok := ret.Get(0).(func() *v1.Node); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Node)
		}
	}
	return r0
}

// MockSkyhookNodeOnly_GetNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNode'
type MockSkyhookNodeOnly_GetNode_Call struct {
	*mock.Call
}

// GetNode is a helper method to define mock.On call
func (_e *MockSkyhookNodeOnly_Expecter) GetNode() *MockSkyhookNodeOnly_GetNode_Call {
	return &MockSkyhookNodeOnly_GetNode_Call{Call: _e.mock.On("GetNode")}
}

func (_c *MockSkyhookNodeOnly_GetNode_Call) Run(run func()) *MockSkyhookNodeOnly_GetNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNodeOnly_GetNode_Call) Return(node *v1.Node) *MockSkyhookNodeOnly_GetNode_Call {
	_c.Call.Return(node)
	return _c
}

func (_c *MockSkyhookNodeOnly_GetNode_Call) RunAndReturn(run func() *v1.Node) *MockSkyhookNodeOnly_GetNode_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function for the type MockSkyhookNodeOnly
func (_mock *MockSkyhookNodeOnly) GetVersion() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSkyhookNodeOnly_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type MockSkyhookNodeOnly_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
func (_e *MockSkyhookNodeOnly_Expecter) GetVersion() *MockSkyhookNodeOnly_GetVersion_Call {
	return &MockSkyhookNodeOnly_GetVersion_Call{Call: _e.mock.On("GetVersion")}
}

func (_c *MockSkyhookNodeOnly_GetVersion_Call) Run(run func()) *MockSkyhookNodeOnly_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNodeOnly_GetVersion_Call) Return(s string) *MockSkyhookNodeOnly_GetVersion_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSkyhookNodeOnly_GetVersion_Call) RunAndReturn(run func() string) *MockSkyhookNodeOnly_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}

// Migrate provides a mock function for the type MockSkyhookNodeOnly
func (_mock *MockSkyhookNodeOnly) Migrate(logger logr.Logger) error {
	ret := _mock.Called(logger)

	if len(ret) == 0 {
		panic("no return value specified for Migrate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(logr.Logger) error); ok {
		r0 = returnFunc(logger)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSkyhookNodeOnly_Migrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migrate'
type MockSkyhookNodeOnly_Migrate_Call struct {
	*mock.Call
}

// Migrate is a helper method to define mock.On call
//   - logger logr.Logger
func (_e *MockSkyhookNodeOnly_Expecter) Migrate(logger interface{}) *MockSkyhookNodeOnly_Migrate_Call {
	return &MockSkyhookNodeOnly_Migrate_Call{Call: _e.mock.On("Migrate", logger)}
}

func (_c *MockSkyhookNodeOnly_Migrate_Call) Run(run func(logger logr.Logger)) *MockSkyhookNodeOnly_Migrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 logr.Logger
		if args[0] != nil {
			arg0 = args[0].(logr.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSkyhookNodeOnly_Migrate_Call) Return(err error) *MockSkyhookNodeOnly_Migrate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSkyhookNodeOnly_Migrate_Call) RunAndReturn(run func(logger logr.Logger) error) *MockSkyhookNodeOnly_Migrate_Call {
	_c.Call.Return(run)
	return _c
}

// PackageStatus provides a mock function for the type MockSkyhookNodeOnly
func (_mock *MockSkyhookNodeOnly) PackageStatus(name string) (*v1alpha1.PackageStatus, bool) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for PackageStatus")
	}

	var r0 *v1alpha1.PackageStatus
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (*v1alpha1.PackageStatus, bool)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *v1alpha1.PackageStatus); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.PackageStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockSkyhookNodeOnly_PackageStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PackageStatus'
type MockSkyhookNodeOnly_PackageStatus_Call struct {
	*mock.Call
}

// PackageStatus is a helper method to define mock.On call
//   - name string
func (_e *MockSkyhookNodeOnly_Expecter) PackageStatus(name interface{}) *MockSkyhookNodeOnly_PackageStatus_Call {
	return &MockSkyhookNodeOnly_PackageStatus_Call{Call: _e.mock.On("PackageStatus", name)}
}

func (_c *MockSkyhookNodeOnly_PackageStatus_Call) Run(run func(name string)) *MockSkyhookNodeOnly_PackageStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSkyhookNodeOnly_PackageStatus_Call) Return(packageStatus *v1alpha1.PackageStatus, b bool) *MockSkyhookNodeOnly_PackageStatus_Call {
	_c.Call.Return(packageStatus, b)
	return _c
}

func (_c *MockSkyhookNodeOnly_PackageStatus_Call) RunAndReturn(run func(name string) (*v1alpha1.PackageStatus, bool)) *MockSkyhookNodeOnly_PackageStatus_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveState provides a mock function for the type MockSkyhookNodeOnly
func (_mock *MockSkyhookNodeOnly) RemoveState(_package v1alpha1.PackageRef) error {
	ret := _mock.Called(_package)

	if len(ret) == 0 {
		panic("no return value specified for RemoveState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(v1alpha1.PackageRef) error); ok {
		r0 = returnFunc(_package)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSkyhookNodeOnly_RemoveState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveState'
type MockSkyhookNodeOnly_RemoveState_Call struct {
	*mock.Call
}

// RemoveState is a helper method to define mock.On call
//   - _package v1alpha1.PackageRef
func (_e *MockSkyhookNodeOnly_Expecter) RemoveState(_package interface{}) *MockSkyhookNodeOnly_RemoveState_Call {
	return &MockSkyhookNodeOnly_RemoveState_Call{Call: _e.mock.On("RemoveState", _package)}
}

func (_c *MockSkyhookNodeOnly_RemoveState_Call) Run(run func(_package v1alpha1.PackageRef)) *MockSkyhookNodeOnly_RemoveState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 v1alpha1.PackageRef
		if args[0] != nil {
			arg0 = args[0].(v1alpha1.PackageRef)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSkyhookNodeOnly_RemoveState_Call) Return(err error) *MockSkyhookNodeOnly_RemoveState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSkyhookNodeOnly_RemoveState_Call) RunAndReturn(run func(_package v1alpha1.PackageRef) error) *MockSkyhookNodeOnly_RemoveState_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTaint provides a mock function for the type MockSkyhookNodeOnly
func (_mock *MockSkyhookNodeOnly) RemoveTaint(key string) {
	_mock.Called(key)
	return
}

// MockSkyhookNodeOnly_RemoveTaint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTaint'
type MockSkyhookNodeOnly_RemoveTaint_Call struct {
	*mock.Call
}

// RemoveTaint is a helper method to define mock.On call
//   - key string
func (_e *MockSkyhookNodeOnly_Expecter) RemoveTaint(key interface{}) *MockSkyhookNodeOnly_RemoveTaint_Call {
	return &MockSkyhookNodeOnly_RemoveTaint_Call{Call: _e.mock.On("RemoveTaint", key)}
}

func (_c *MockSkyhookNodeOnly_RemoveTaint_Call) Run(run func(key string)) *MockSkyhookNodeOnly_RemoveTaint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSkyhookNodeOnly_RemoveTaint_Call) Return() *MockSkyhookNodeOnly_RemoveTaint_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSkyhookNodeOnly_RemoveTaint_Call) RunAndReturn(run func(key string)) *MockSkyhookNodeOnly_RemoveTaint_Call {
	_c.Run(run)
	return _c
}

// Reset provides a mock function for the type MockSkyhookNodeOnly
func (_mock *MockSkyhookNodeOnly) Reset() {
	_mock.Called()
	return
}

// MockSkyhookNodeOnly_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type MockSkyhookNodeOnly_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
func (_e *MockSkyhookNodeOnly_Expecter) Reset() *MockSkyhookNodeOnly_Reset_Call {
	return &MockSkyhookNodeOnly_Reset_Call{Call: _e.mock.On("Reset")}
}

func (_c *MockSkyhookNodeOnly_Reset_Call) Run(run func()) *MockSkyhookNodeOnly_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNodeOnly_Reset_Call) Return() *MockSkyhookNodeOnly_Reset_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSkyhookNodeOnly_Reset_Call) RunAndReturn(run func()) *MockSkyhookNodeOnly_Reset_Call {
	_c.Run(run)
	return _c
}

// SetState provides a mock function for the type MockSkyhookNodeOnly
func (_mock *MockSkyhookNodeOnly) SetState(state v1alpha1.NodeState) error {
	ret := _mock.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for SetState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(v1alpha1.NodeState) error); ok {
		r0 = returnFunc(state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSkyhookNodeOnly_SetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetState'
type MockSkyhookNodeOnly_SetState_Call struct {
	*mock.Call
}

// SetState is a helper method to define mock.On call
//   - state v1alpha1.NodeState
func (_e *MockSkyhookNodeOnly_Expecter) SetState(state interface{}) *MockSkyhookNodeOnly_SetState_Call {
	return &MockSkyhookNodeOnly_SetState_Call{Call: _e.mock.On("SetState", state)}
}

func (_c *MockSkyhookNodeOnly_SetState_Call) Run(run func(state v1alpha1.NodeState)) *MockSkyhookNodeOnly_SetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 v1alpha1.NodeState
		if args[0] != nil {
			arg0 = args[0].(v1alpha1.NodeState)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSkyhookNodeOnly_SetState_Call) Return(err error) *MockSkyhookNodeOnly_SetState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSkyhookNodeOnly_SetState_Call) RunAndReturn(run func(state v1alpha1.NodeState) error) *MockSkyhookNodeOnly_SetState_Call {
	_c.Call.Return(run)
	return _c
}

// SetStatus provides a mock function for the type MockSkyhookNodeOnly
func (_mock *MockSkyhookNodeOnly) SetStatus(status v1alpha1.Status) {
	_mock.Called(status)
	return
}

// MockSkyhookNodeOnly_SetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatus'
type MockSkyhookNodeOnly_SetStatus_Call struct {
	*mock.Call
}

// SetStatus is a helper method to define mock.On call
//   - status v1alpha1.Status
func (_e *MockSkyhookNodeOnly_Expecter) SetStatus(status interface{}) *MockSkyhookNodeOnly_SetStatus_Call {
	return &MockSkyhookNodeOnly_SetStatus_Call{Call: _e.mock.On("SetStatus", status)}
}

func (_c *MockSkyhookNodeOnly_SetStatus_Call) Run(run func(status v1alpha1.Status)) *MockSkyhookNodeOnly_SetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 v1alpha1.Status
		if args[0] != nil {
			arg0 = args[0].(v1alpha1.Status)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSkyhookNodeOnly_SetStatus_Call) Return() *MockSkyhookNodeOnly_SetStatus_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSkyhookNodeOnly_SetStatus_Call) RunAndReturn(run func(status v1alpha1.Status)) *MockSkyhookNodeOnly_SetStatus_Call {
	_c.Run(run)
	return _c
}

// SetVersion provides a mock function for the type MockSkyhookNodeOnly
func (_mock *MockSkyhookNodeOnly) SetVersion() {
	_mock.Called()
	return
}

// MockSkyhookNodeOnly_SetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVersion'
type MockSkyhookNodeOnly_SetVersion_Call struct {
	*mock.Call
}

// SetVersion is a helper method to define mock.On call
func (_e *MockSkyhookNodeOnly_Expecter) SetVersion() *MockSkyhookNodeOnly_SetVersion_Call {
	return &MockSkyhookNodeOnly_SetVersion_Call{Call: _e.mock.On("SetVersion")}
}

func (_c *MockSkyhookNodeOnly_SetVersion_Call) Run(run func()) *MockSkyhookNodeOnly_SetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNodeOnly_SetVersion_Call) Return() *MockSkyhookNodeOnly_SetVersion_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSkyhookNodeOnly_SetVersion_Call) RunAndReturn(run func()) *MockSkyhookNodeOnly_SetVersion_Call {
	_c.Run(run)
	return _c
}

// State provides a mock function for the type MockSkyhookNodeOnly
func (_mock *MockSkyhookNodeOnly) State() (v1alpha1.NodeState, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 v1alpha1.NodeState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (v1alpha1.NodeState, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() v1alpha1.NodeState); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.NodeState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSkyhookNodeOnly_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type MockSkyhookNodeOnly_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
func (_e *MockSkyhookNodeOnly_Expecter) State() *MockSkyhookNodeOnly_State_Call {
	return &MockSkyhookNodeOnly_State_Call{Call: _e.mock.On("State")}
}

func (_c *MockSkyhookNodeOnly_State_Call) Run(run func()) *MockSkyhookNodeOnly_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNodeOnly_State_Call) Return(nodeState v1alpha1.NodeState, err error) *MockSkyhookNodeOnly_State_Call {
	_c.Call.Return(nodeState, err)
	return _c
}

func (_c *MockSkyhookNodeOnly_State_Call) RunAndReturn(run func() (v1alpha1.NodeState, error)) *MockSkyhookNodeOnly_State_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockSkyhookNodeOnly
func (_mock *MockSkyhookNodeOnly) Status() v1alpha1.Status {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 v1alpha1.Status
	if returnFunc, ok := ret.Get(0).(func() v1alpha1.Status); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(v1alpha1.Status)
	}
	return r0
}

// MockSkyhookNodeOnly_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockSkyhookNodeOnly_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *MockSkyhookNodeOnly_Expecter) Status() *MockSkyhookNodeOnly_Status_Call {
	return &MockSkyhookNodeOnly_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *MockSkyhookNodeOnly_Status_Call) Run(run func()) *MockSkyhookNodeOnly_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNodeOnly_Status_Call) Return(status v1alpha1.Status) *MockSkyhookNodeOnly_Status_Call {
	_c.Call.Return(status)
	return _c
}

func (_c *MockSkyhookNodeOnly_Status_Call) RunAndReturn(run func() v1alpha1.Status) *MockSkyhookNodeOnly_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Taint provides a mock function for the type MockSkyhookNodeOnly
func (_mock *MockSkyhookNodeOnly) Taint(key string) {
	_mock.Called(key)
	return
}

// MockSkyhookNodeOnly_Taint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Taint'
type MockSkyhookNodeOnly_Taint_Call struct {
	*mock.Call
}

// Taint is a helper method to define mock.On call
//   - key string
func (_e *MockSkyhookNodeOnly_Expecter) Taint(key interface{}) *MockSkyhookNodeOnly_Taint_Call {
	return &MockSkyhookNodeOnly_Taint_Call{Call: _e.mock.On("Taint", key)}
}

func (_c *MockSkyhookNodeOnly_Taint_Call) Run(run func(key string)) *MockSkyhookNodeOnly_Taint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSkyhookNodeOnly_Taint_Call) Return() *MockSkyhookNodeOnly_Taint_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSkyhookNodeOnly_Taint_Call) RunAndReturn(run func(key string)) *MockSkyhookNodeOnly_Taint_Call {
	_c.Run(run)
	return _c
}

// Uncordon provides a mock function for the type MockSkyhookNodeOnly
func (_mock *MockSkyhookNodeOnly) Uncordon() {
	_mock.Called()
	return
}

// MockSkyhookNodeOnly_Uncordon_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Uncordon'
type MockSkyhookNodeOnly_Uncordon_Call struct {
	*mock.Call
}

// Uncordon is a helper method to define mock.On call
func (_e *MockSkyhookNodeOnly_Expecter) Uncordon() *MockSkyhookNodeOnly_Uncordon_Call {
	return &MockSkyhookNodeOnly_Uncordon_Call{Call: _e.mock.On("Uncordon")}
}

func (_c *MockSkyhookNodeOnly_Uncordon_Call) Run(run func()) *MockSkyhookNodeOnly_Uncordon_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSkyhookNodeOnly_Uncordon_Call) Return() *MockSkyhookNodeOnly_Uncordon_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSkyhookNodeOnly_Uncordon_Call) RunAndReturn(run func()) *MockSkyhookNodeOnly_Uncordon_Call {
	_c.Run(run)
	return _c
}

// Upsert provides a mock function for the type MockSkyhookNodeOnly
func (_mock *MockSkyhookNodeOnly) Upsert(_package v1alpha1.PackageRef, image string, state v1alpha1.State, stage v1alpha1.Stage, restarts int32, containerSHA string) error {
	ret := _mock.Called(_package, image, state, stage, restarts, containerSHA)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(v1alpha1.PackageRef, string, v1alpha1.State, v1alpha1.Stage, int32, string) error); ok {
		r0 = returnFunc(_package, image, state, stage, restarts, containerSHA)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSkyhookNodeOnly_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockSkyhookNodeOnly_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - _package v1alpha1.PackageRef
//   - image string
//   - state v1alpha1.State
//   - stage v1alpha1.Stage
//   - restarts int32
//   - containerSHA string
func (_e *MockSkyhookNodeOnly_Expecter) Upsert(_package interface{}, image interface{}, state interface{}, stage interface{}, restarts interface{}, containerSHA interface{}) *MockSkyhookNodeOnly_Upsert_Call {
	return &MockSkyhookNodeOnly_Upsert_Call{Call: _e.mock.On("Upsert", _package, image, state, stage, restarts, containerSHA)}
}

func (_c *MockSkyhookNodeOnly_Upsert_Call) Run(run func(_package v1alpha1.PackageRef, image string, state v1alpha1.State, stage v1alpha1.Stage, restarts int32, containerSHA string)) *MockSkyhookNodeOnly_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 v1alpha1.PackageRef
		if args[0] != nil {
			arg0 = args[0].(v1alpha1.PackageRef)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 v1alpha1.State
		if args[2] != nil {
			arg2 = args[2].(v1alpha1.State)
		}
		var arg3 v1alpha1.Stage
		if args[3] != nil {
			arg3 = args[3].(v1alpha1.Stage)
		}
		var arg4 int32
		if args[4] != nil {
			arg4 = args[4].(int32)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockSkyhookNodeOnly_Upsert_Call) Return(err error) *MockSkyhookNodeOnly_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSkyhookNodeOnly_Upsert_Call) RunAndReturn(run func(_package v1alpha1.PackageRef, image string, state v1alpha1.State, stage v1alpha1.Stage, restarts int32, containerSHA string) error) *MockSkyhookNodeOnly_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
