apiVersion: skyhook.nvidia.com/v1alpha1
kind: Skyhook
metadata:
  labels:
    app.kubernetes.io/part-of: skyhook-operator
    app.kubernetes.io/created-by: skyhook-operator
  name: taint-scheduling
spec:
  nodeSelectors:
    matchLabels:
      skyhook.nvidia.com/test-node: skyhooke2e
  additionalTolerations:
    - key: nvidia.com/gpu
      effect: NoSchedule
  packages:
    spencer:
      version: "3.2.3"
      image: ghcr.io/nvidia/skyhook/agentless

