#!/usr/bin/env bash

# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# gen_nodewright.sh re-derives the nodewright.nvidia.com API group
# (api/nodewright/v1alpha1) from the legacy skyhook.nvidia.com API group
# (api/v1alpha1) by applying a deterministic rename transform.
#
# WHY THIS EXISTS: the nodewright group is a schema-frozen mirror of the legacy
# Skyhook group during the Skyhook -> NodeWright migration. Hand-maintaining the
# copy let it silently drift from upstream (e.g. a DrainConfig field and an
# image-parsing rewrite landed in the legacy types but not the copy). Generating
# the copy from the legacy files makes drift impossible: change the legacy
# schema and re-run this script (wired into `make generate`), and the mirror
# tracks it. A verify target (`make verify-nodewright-gen`) fails CI if the
# checked-in copy is stale.
#
# The transform is a pure, deterministic textual rename (see RULES below). It is
# NOT a semantic rewrite: everything the legacy files say is carried through with
# skyhook renamed to nodewright. Run twice, it produces identical output (the
# output is a function of the legacy input only), so the verify check is stable.
#
# ONE NON-PURE-RENAME STEP (the "de-deprecate" step, dedeprecate below): the legacy
# webhooks carry a migration DEPRECATION WARNING that nudges users from
# skyhook.nvidia.com to nodewright.nvidia.com. A pure rename would turn that into a
# self-referential warning on the NEW group ("NodeWright is deprecated; migrate to
# NodeWright") that fires on every NodeWright create/update, including the ones the
# mirror controller stamps out. That is legacy-only intent a rename cannot express,
# so the generator drops it: the deprecation const is removed and its use is reduced
# to an empty admission.Warnings. This reproduces exactly what the new group's
# webhook is meant to do (and what the original hand-written copy did). It is the one
# place the transform is more than a rename; it is anchored on the stable
# *DeprecationWarning token, and both the unit tests and `make verify-nodewright-gen`
# will catch it if the legacy deprecation shape ever changes out from under it.

set -euo pipefail

# Resolve repo-relative paths from this script's location so it works from any cwd.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
OPERATOR_DIR="${REPO_DIR}/operator"

SRC_DIR="${OPERATOR_DIR}/api/v1alpha1"
DST_DIR="${OPERATOR_DIR}/api/nodewright/v1alpha1"

GEN_MARKER="// Code generated by gen_nodewright; DO NOT EDIT."

# Source -> destination file map. Only the schema/validation source files are
# generated. zz_generated.deepcopy.go is owned by controller-gen; the conversion
# files (nodewright_conversion*.go) live only in the legacy package and import the
# new group, so they are not mirrored.
declare -a SRC_FILES=(
	"groupversion_info.go"
	"skyhook_types.go"
	"deployment_policy_types.go"
	"skyhook_webhook.go"
	"deployment_policy_webhook.go"
)
declare -a DST_FILES=(
	"groupversion_info.go"
	"nodewright_types.go"
	"deployment_policy_types.go"
	"nodewright_webhook.go"
	"deployment_policy_webhook.go"
)

# rename applies the deterministic transform to stdin -> stdout.
#
# RULES (order matters):
#  1. DeploymentPolicy webhook name disambiguation. The new group's
#     DeploymentPolicy webhooks MUST NOT collide with the legacy ones in the
#     merged config/webhook/manifests.yaml, so their names get a -nodewright
#     suffix. Done first, before the group rename touches the surrounding marker.
#  2. Webhook marker path segments and skyhook-specific names/resources. These use
#     dashes ("-skyhook-nvidia-com-", "mskyhook.kb.io", "resources=skyhooks",
#     path-trailing "-v1alpha1-skyhook"), which the dotted-group rule (4) does not
#     match, so they are handled explicitly.
#  3. (folded into 2)
#  4. Group name: the dotted "skyhook.nvidia.com" -> "nodewright.nvidia.com".
#     Covers +groupName, GroupVersion, groups= markers, METADATA_PREFIX, comments,
#     and string literals.
#  5. PascalCase type rename: capital-S "Skyhook" -> "NodeWright" (case sensitive).
#     Catches Skyhook, SkyhookSpec, SkyhookStatus, SkyhookList, SkyhookWebhook and
#     PascalCase identifiers embedding them (e.g. referencingSkyhooks). Lowercase
#     "skyhook" (skyhookName, skyhooklog, skyhookv1, import paths) and ALL-CAPS
#     "SKYHOOK" (env var names like SKYHOOK_NODE_ORDER) are intentionally left
#     alone: those names have not moved in the migration.
rename() {
	sed -E \
		-e 's/mdeploymentpolicy\.kb\.io/mdeploymentpolicy-nodewright.kb.io/g' \
		-e 's/vdeploymentpolicy\.kb\.io/vdeploymentpolicy-nodewright.kb.io/g' \
		-e 's/-skyhook-nvidia-com-/-nodewright-nvidia-com-/g' \
		-e 's/-v1alpha1-skyhook,/-v1alpha1-nodewright,/g' \
		-e 's/resources=skyhooks/resources=nodewrights/g' \
		-e 's/mskyhook\.kb\.io/mnodewright.kb.io/g' \
		-e 's/vskyhook\.kb\.io/vnodewright.kb.io/g' \
		-e 's/skyhook\.nvidia\.com/nodewright.nvidia.com/g' \
		-e 's/Skyhook/NodeWright/g'
}

# dedeprecate removes the legacy-only migration deprecation warning from a renamed
# webhook file (see the header comment for why). It:
#   - deletes the "<name>DeprecationWarning" doc comment + const block, and
#   - turns "warnings := admission.Warnings{<name>DeprecationWarning}" into an empty
#     "var warnings admission.Warnings" (ValidateCreate/ValidateUpdate keep their
#     warnings variable, now starting empty), and
#   - turns any inline "return admission.Warnings{<name>DeprecationWarning}, ..."
#     (the DeploymentPolicy webhook form) into "return nil, ...".
# The "warnings :=" substitution runs before the inline one so it is not clobbered.
dedeprecate() {
	perl -0777 -pe '
		s/\n\/\/ \w+DeprecationWarning is surfaced.*?removed in a future release\."\n/\n/s;
		s/warnings := admission\.Warnings\{\w+DeprecationWarning\}/var warnings admission.Warnings/g;
		s/admission\.Warnings\{\w+DeprecationWarning\}/nil/g;
	'
}

# insert_marker prints the generated-code marker just below the license header
# (the closing " */" of the SPDX block) so `go` tooling and golangci-lint treat
# the file as generated, while the license checker still sees the SPDX block on
# top.
insert_marker() {
	awk -v marker="${GEN_MARKER}" '
		{ print }
		!done && $0 == " */" { print ""; print marker; done=1 }
	'
}

echo "gen_nodewright: regenerating ${DST_DIR} from ${SRC_DIR}"
for i in "${!SRC_FILES[@]}"; do
	src="${SRC_DIR}/${SRC_FILES[$i]}"
	dst="${DST_DIR}/${DST_FILES[$i]}"
	# The webhook files carry the legacy-only deprecation warning; strip it.
	if [[ "${DST_FILES[$i]}" == *webhook.go ]]; then
		rename <"${src}" | dedeprecate | insert_marker >"${dst}"
	else
		rename <"${src}" | insert_marker >"${dst}"
	fi
	echo "  ${SRC_FILES[$i]} -> $(basename "${dst}")"
done

# gofmt only the generated source files so the output is canonical (collapses the
# blank line the deprecation-const removal leaves behind). We list DST_FILES
# explicitly rather than DST_DIR/*.go so we never touch zz_generated.deepcopy.go
# (owned by controller-gen). The license header is copied verbatim from the
# already-canonical legacy source, so no separate license pass is needed here (and
# a repo-wide format_license would rewrite this running script and corrupt it).
for f in "${DST_FILES[@]}"; do
	"$(go env GOROOT)/bin/gofmt" -w "${DST_DIR}/${f}"
done

echo "gen_nodewright: done"
