{
 "title": "Skyhook Package Details Dashboard",
 "tags": [
  "skyhook",
  "packages"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "skyhook",
    "query": {
     "query": "label_values(skyhook_package_complete_count, skyhook_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Package Stage Heatmap",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "skyhook_package_count" }
   ]
  },
  {
   "title": "Package Status Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (package_name) (skyhook_package_count{state=\"complete\"})",
     "legendFormat": "{{package_name}} - Complete"
    },
    {
     "expr": "sum by (package_name) (skyhook_package_count{state=\"in_progress\"})",
     "legendFormat": "{{package_name}} - In Progress"
    },
    {
     "expr": "sum by (package_name) (skyhook_package_count{state=\"erroring\"})",
     "legendFormat": "{{package_name}} - Error"
    }
   ]
  },
  {
   "title": "Package Restart Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (package_name) (skyhook_package_restarts_count)",
     "legendFormat": "{{package_name}} Restarts"
    }
   ]
  },
  {
   "title": "Package Status Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "skyhook_package_count{state=\"complete\"}"
    },
    {
     "expr": "skyhook_package_count{state=\"in_progress\"}"
    },
    {
     "expr": "skyhook_package_count{state=\"erroring\"}"
    },
    { "expr": "skyhook_package_restarts_count" }
   ]
  },
  {
   "title": "Package State Timeline (Swim Lanes)",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "skyhook_package_count{stage=\"apply\"}",
     "legendFormat": "{{package_name}}-{{package_version}} Apply {{state}}"
    },
    {
     "expr": "skyhook_package_count{stage=\"config\"}",
     "legendFormat": "{{package_name}}-{{package_version}} Config {{state}}"
    },
    {
     "expr": "skyhook_package_count{stage=\"interrupt\"}",
     "legendFormat": "{{package_name}}-{{package_version}} Interrupt {{state}}"
    }
   ]
  }
 ]
}