apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: default
spec:
  containers:
  - args:
      - -c
      - import time; time.sleep(100000)
      #- import os; print("hello"); os.chroot("/root"); os.makedirs("/root/test")
    command:
      - python
    image: ghcr.io/nvidia/skyhook/agent:25.04.12-000534-
    imagePullPolicy: Always
    name: debug
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 500m
        memory: 256Mi
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /home/nvs/root
      mountPropagation: HostToContainer
      name: root-mount
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  hostPID: true
  imagePullSecrets:
  - name: node-init-secret
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: #{}
    runAsUser: 0
    runAsGroup: 0
    #runAsNonRoot: true
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /
      type: ""
    name: root-mount
