# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: multi-compartment-deployment-policy
spec:
  description: |
    Tests deployment policy with multiple compartments using exponential strategy.
    Verifies compartment assignment, budget enforcement, and batch progression.
  timeouts:
    assert: 600s
    exec: 300s  # Increased for 15-node rollout
  steps:
  
  - name: setup-nodes
    try:
    - script:
        content: |
          chmod +x setup-nodes.sh cleanup-nodes.sh
          ./setup-nodes.sh
  
  - name: apply-resources
    try:
    - apply:
        file: deployment-policy.yaml
    - apply:
        file: skyhook.yaml
    - script:
        content: |
          echo "Waiting for Skyhook to initialize..."
          sleep 10
  
  - name: verify-compartments-created
    try:
    - script:
        content: |
          echo "=== Verifying compartments ==="
          
          # Check that all expected compartments exist
          COMPARTMENTS=$(kubectl get skyhook multi-compartment-test -o jsonpath='{.status.compartmentStatuses}' | jq -r 'keys[]' | sort)
          echo "Compartments found: $COMPARTMENTS"
          
          # Should have: critical, standard, test (possibly __default__ if any nodes unmatched)
          CRITICAL=$(echo "$COMPARTMENTS" | grep -c "critical" || echo "0")
          STANDARD=$(echo "$COMPARTMENTS" | grep -c "standard" || echo "0")
          TEST=$(echo "$COMPARTMENTS" | grep -c "test" || echo "0")
          
          if [ "$CRITICAL" != "1" ] || [ "$STANDARD" != "1" ] || [ "$TEST" != "1" ]; then
            echo "ERROR: Missing expected compartments"
            echo "Expected: critical, standard, test"
            echo "Found: $COMPARTMENTS"
            exit 1
          fi
          
          echo "✓ All compartments created"
    - script:
        content: |
          echo "=== Verifying compartment metrics ==="
          
          # Verify matched nodes metrics for each compartment
          ../metrics_test.py skyhook_rollout_matched_nodes 5 -t skyhook_name=multi-compartment-test -t policy_name=multi-tier-policy -t compartment_name=critical -t strategy=exponential
          ../metrics_test.py skyhook_rollout_matched_nodes 6 -t skyhook_name=multi-compartment-test -t policy_name=multi-tier-policy -t compartment_name=standard -t strategy=exponential
          ../metrics_test.py skyhook_rollout_matched_nodes 4 -t skyhook_name=multi-compartment-test -t policy_name=multi-tier-policy -t compartment_name=test -t strategy=exponential
          
          echo "✓ Compartment metrics verified"
  
  - name: verify-node-counts
    try:
    - script:
        content: |
          echo "=== Verifying node distribution ==="
          
          CRITICAL_NODES=$(kubectl get skyhook multi-compartment-test -o jsonpath='{.status.compartmentStatuses.critical.matched}')
          STANDARD_NODES=$(kubectl get skyhook multi-compartment-test -o jsonpath='{.status.compartmentStatuses.standard.matched}')
          TEST_NODES=$(kubectl get skyhook multi-compartment-test -o jsonpath='{.status.compartmentStatuses.test.matched}')
          
          echo "Critical nodes: $CRITICAL_NODES (expected: 5)"
          echo "Standard nodes: $STANDARD_NODES (expected: 6)"
          echo "Test nodes: $TEST_NODES (expected: 4)"
          
          if [ "$CRITICAL_NODES" != "5" ] || [ "$STANDARD_NODES" != "6" ] || [ "$TEST_NODES" != "4" ]; then
            echo "ERROR: Incorrect node distribution"
            kubectl get skyhook multi-compartment-test -o yaml
            exit 1
          fi
          
          echo "✓ Node distribution correct"
    - script:
        content: |
          echo "=== Verifying ceiling metrics ==="
          
          # Verify ceiling (budget) for each compartment
          # Critical: count=2 (explicit)
          # Standard: 33% of 6 = 1.98 → floor = 1
          # Test: 50% of 4 = 2
          ../metrics_test.py skyhook_rollout_ceiling 2 -t skyhook_name=multi-compartment-test -t policy_name=multi-tier-policy -t compartment_name=critical -t strategy=exponential
          ../metrics_test.py skyhook_rollout_ceiling 1 -t skyhook_name=multi-compartment-test -t policy_name=multi-tier-policy -t compartment_name=standard -t strategy=exponential
          ../metrics_test.py skyhook_rollout_ceiling 2 -t skyhook_name=multi-compartment-test -t policy_name=multi-tier-policy -t compartment_name=test -t strategy=exponential
          
          echo "✓ Ceiling metrics verified"
  
  - name: monitor-rollout
    try:
    - script:
        content: |
          echo "=== Monitoring rollout progress ==="
          
          for i in {1..120}; do
            COMPLETE_NODES=$(kubectl get skyhook multi-compartment-test \
              -o jsonpath='{.status.completeNodes}' 2>/dev/null || echo "0/15")
            TOTAL_COMPLETE=$(echo "$COMPLETE_NODES" | cut -d'/' -f1)
            TOTAL_IN_PROGRESS=$(kubectl get skyhook multi-compartment-test \
              -o jsonpath='{.status.nodesInProgress}' 2>/dev/null || echo "0")
            
            # Get compartment progress
            CRIT_COMPLETE=$(kubectl get skyhook multi-compartment-test \
              -o jsonpath='{.status.compartmentStatuses.critical.completed}' 2>/dev/null || echo "0")
            STD_COMPLETE=$(kubectl get skyhook multi-compartment-test \
              -o jsonpath='{.status.compartmentStatuses.standard.completed}' 2>/dev/null || echo "0")
            TEST_COMPLETE=$(kubectl get skyhook multi-compartment-test \
              -o jsonpath='{.status.compartmentStatuses.test.completed}' 2>/dev/null || echo "0")
            
            echo "[$i/120] Complete: $TOTAL_COMPLETE/15 | InProgress: $TOTAL_IN_PROGRESS | Compartments: crit=$CRIT_COMPLETE std=$STD_COMPLETE test=$TEST_COMPLETE"
            
            if [ "$TOTAL_COMPLETE" == "15" ]; then
              echo "✓ All nodes completed!"
              break
            fi
            
            if [ $i -eq 120 ]; then
              echo "ERROR: Timeout waiting for completion"
              kubectl get skyhook multi-compartment-test -o yaml
              exit 1
            fi
            
            sleep 5
          done
  
  - name: verify-final-state
    try:
    - script:
        content: |
          echo "=== Verifying final state ==="
          
          # Critical compartment
          echo "Critical compartment:"
          kubectl get skyhook multi-compartment-test -o jsonpath='{.status.compartmentStatuses.critical}' | jq .
          
          CRIT_COMPLETE=$(kubectl get skyhook multi-compartment-test -o jsonpath='{.status.compartmentStatuses.critical.completed}')
          CRIT_FAILED=$(kubectl get skyhook multi-compartment-test -o jsonpath='{.status.compartmentStatuses.critical.failed}' || echo "0")
          
          if [ "$CRIT_COMPLETE" != "5" ]; then
            echo "ERROR: Critical compartment - completed: $CRIT_COMPLETE (expected 5), failed: $CRIT_FAILED"
            exit 1
          fi
          
          # Standard compartment
          echo "Standard compartment:"
          kubectl get skyhook multi-compartment-test -o jsonpath='{.status.compartmentStatuses.standard}' | jq .
          
          STD_COMPLETE=$(kubectl get skyhook multi-compartment-test -o jsonpath='{.status.compartmentStatuses.standard.completed}')
          STD_FAILED=$(kubectl get skyhook multi-compartment-test -o jsonpath='{.status.compartmentStatuses.standard.failed}' || echo "0")
          
          if [ "$STD_COMPLETE" != "6" ]; then
            echo "ERROR: Standard compartment - completed: $STD_COMPLETE (expected 6), failed: $STD_FAILED"
            exit 1
          fi
          
          # Test compartment
          echo "Test compartment:"
          kubectl get skyhook multi-compartment-test -o jsonpath='{.status.compartmentStatuses.test}' | jq .
          
          TEST_COMPLETE=$(kubectl get skyhook multi-compartment-test -o jsonpath='{.status.compartmentStatuses.test.completed}')
          TEST_FAILED=$(kubectl get skyhook multi-compartment-test -o jsonpath='{.status.compartmentStatuses.test.failed}' || echo "0")
          
          if [ "$TEST_COMPLETE" != "4" ]; then
            echo "ERROR: Test compartment - completed: $TEST_COMPLETE (expected 4), failed: $TEST_FAILED"
            exit 1
          fi
          
          # Overall status
          COMPLETE_NODES=$(kubectl get skyhook multi-compartment-test -o jsonpath='{.status.completeNodes}')
          TOTAL_COMPLETE=$(echo "$COMPLETE_NODES" | cut -d'/' -f1)
          
          if [ "$TOTAL_COMPLETE" != "15" ]; then
            echo "ERROR: Expected 15 complete nodes, got $TOTAL_COMPLETE (from $COMPLETE_NODES)"
            exit 1
          fi
          
          echo ""
          echo "✓✓✓ All compartments completed successfully! ✓✓✓"
    - script:
        content: |
          echo "=== Verifying final metrics ==="
          
          # All compartments should have 100% completion and 0 in progress
          ../metrics_test.py skyhook_rollout_completed 5 -t skyhook_name=multi-compartment-test -t policy_name=multi-tier-policy -t compartment_name=critical -t strategy=exponential
          ../metrics_test.py skyhook_rollout_in_progress 0 -t skyhook_name=multi-compartment-test -t policy_name=multi-tier-policy -t compartment_name=critical -t strategy=exponential
          ../metrics_test.py skyhook_rollout_progress_percent 100 -t skyhook_name=multi-compartment-test -t policy_name=multi-tier-policy -t compartment_name=critical -t strategy=exponential
          
          ../metrics_test.py skyhook_rollout_completed 6 -t skyhook_name=multi-compartment-test -t policy_name=multi-tier-policy -t compartment_name=standard -t strategy=exponential
          ../metrics_test.py skyhook_rollout_in_progress 0 -t skyhook_name=multi-compartment-test -t policy_name=multi-tier-policy -t compartment_name=standard -t strategy=exponential
          ../metrics_test.py skyhook_rollout_progress_percent 100 -t skyhook_name=multi-compartment-test -t policy_name=multi-tier-policy -t compartment_name=standard -t strategy=exponential
          
          ../metrics_test.py skyhook_rollout_completed 4 -t skyhook_name=multi-compartment-test -t policy_name=multi-tier-policy -t compartment_name=test -t strategy=exponential
          ../metrics_test.py skyhook_rollout_in_progress 0 -t skyhook_name=multi-compartment-test -t policy_name=multi-tier-policy -t compartment_name=test -t strategy=exponential
          ../metrics_test.py skyhook_rollout_progress_percent 100 -t skyhook_name=multi-compartment-test -t policy_name=multi-tier-policy -t compartment_name=test -t strategy=exponential
          
          # Verify batch state metrics exist (current_batch and consecutive_failures should be present)
          ../metrics_test.py skyhook_rollout_consecutive_failures 0 -t skyhook_name=multi-compartment-test -t policy_name=multi-tier-policy -t compartment_name=critical -t strategy=exponential
          ../metrics_test.py skyhook_rollout_consecutive_failures 0 -t skyhook_name=multi-compartment-test -t policy_name=multi-tier-policy -t compartment_name=standard -t strategy=exponential
          ../metrics_test.py skyhook_rollout_consecutive_failures 0 -t skyhook_name=multi-compartment-test -t policy_name=multi-tier-policy -t compartment_name=test -t strategy=exponential
          
          echo "✓ All final metrics verified!"
  
  - name: cleanup
    try:
    - script:
        content: ./cleanup-nodes.sh || true
    - delete:
        ref:
          apiVersion: skyhook.nvidia.com/v1alpha1
          kind: Skyhook
          name: multi-compartment-test
    - delete:
        ref:
          apiVersion: skyhook.nvidia.com/v1alpha1
          kind: DeploymentPolicy
          name: multi-tier-policy
