apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skyhook-operator-proxy-role
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: skyhook-operator
    app.kubernetes.io/part-of: skyhook-operator
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: skyhook-operator-proxy-rolebinding
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: skyhook-operator
    app.kubernetes.io/part-of: skyhook-operator
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: skyhook-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "chart.fullname" . }}-controller-manager
  namespace: '{{ .Release.Namespace }}'