# three node (two workers) local kind cluster config for testing
# makefile references this to create this cluster
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
